import React, { useState } from 'react';
import { useDesignSystem } from '../../hooks/useDesignSystem';
import { SOM_THEMES, SOM_VISUAL_STYLES } from '../../lib/designSystemPresets';
import { ThemeId, VisualStyleId } from '../../types/designSystem';
import { Palette, Sparkles, Check, X, ArrowRight, Sliders, Settings, Layers, LayoutGrid } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import LoginControlCenter from '../LoginControlCenter';

interface QuickDesignLauncherModalProps { isOpen:boolean; onClose:()=>void; onOpenFullSettings?:()=>void; }
export const QuickDesignLauncherModal:React.FC<QuickDesignLauncherModalProps>=({isOpen,onClose,onOpenFullSettings})=>{
 const {designConfig,setThemePreset,setVisualStyle}=useDesignSystem(); const [activeSubTab,setActiveSubTab]=useState<'themes'|'styles'|'login'>('themes'); if(!isOpen)return null;
 return <AnimatePresence><div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-sm"><motion.div initial={{opacity:0,scale:.95,y:15}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.95,y:15}} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl w-full max-w-5xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
  <div className="p-5 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-gradient-to-r from-brand-soft via-transparent to-transparent"><div className="flex items-center space-x-3"><div className="p-2.5 bg-brand text-white rounded-2xl shadow-sm"><Palette size={20}/></div><div><h3 className="text-base font-black text-slate-900 dark:text-white">สตูดิโอธีม & Login</h3><p className="text-xs text-slate-500 dark:text-slate-400">เปลี่ยนดีไซน์ระบบและจัดการหน้าเข้าสู่ระบบ</p></div></div><button onClick={onClose} className="p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800"><X size={18}/></button></div>
  <div className="px-6 pt-4 pb-1 flex items-center justify-between gap-2 border-b border-slate-100 dark:border-slate-800/80"><div className="flex flex-wrap items-center gap-2 bg-slate-100 dark:bg-slate-800/80 p-1 rounded-2xl"><button onClick={()=>setActiveSubTab('themes')} className={`px-4 py-2 rounded-xl text-xs font-bold ${activeSubTab==='themes'?'bg-white dark:bg-slate-700 shadow-xs':''}`}>🎨 ธีมสี</button><button onClick={()=>setActiveSubTab('styles')} className={`px-4 py-2 rounded-xl text-xs font-bold ${activeSubTab==='styles'?'bg-white dark:bg-slate-700 shadow-xs':''}`}>💎 Visual Styles</button><button onClick={()=>setActiveSubTab('login')} className={`px-4 py-2 rounded-xl text-xs font-bold ${activeSubTab==='login'?'bg-white dark:bg-slate-700 shadow-xs':''}`}>✨ Login Control</button></div>{onOpenFullSettings&&<button onClick={()=>{onClose();onOpenFullSettings();}} className="text-xs font-bold text-brand hover:underline flex items-center gap-1"><Sliders size={13}/> สตูดิโอปรับแต่งแบบละเอียด</button>}</div>
  <div className="p-6 overflow-y-auto flex-1">{activeSubTab==='login'?<LoginControlCenter/>:activeSubTab==='themes'?<div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">{SOM_THEMES.map(theme=>{const selected=designConfig.themeId===theme.id;return <button key={theme.id} onClick={()=>setThemePreset(theme.id)} className={`p-3.5 rounded-2xl border-2 text-left flex items-center justify-between ${selected?'border-brand bg-brand-soft/20 shadow-md':'border-slate-200/80 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/40'}`}><div className="flex items-center space-x-3"><div className="w-9 h-9 rounded-xl border-2 border-white dark:border-slate-800 flex items-center justify-center" style={{backgroundColor:theme.colors.primary}}>{selected&&<Check size={16} className="text-white"/>}</div><div><div className="flex items-center gap-1.5"><span className="text-xs font-black text-slate-900 dark:text-white">{theme.name}</span><span className="text-[9px] px-1.5 bg-slate-200 dark:bg-slate-800 rounded font-bold">{theme.badge}</span></div><span className="text-[10px] text-slate-400 block">{theme.tagline}</span></div></div><div className="flex gap-1"><div className="w-3.5 h-3.5 rounded-full" style={{backgroundColor:theme.colors.secondary}}/><div className="w-3.5 h-3.5 rounded-full" style={{backgroundColor:theme.colors.accent}}/></div></button>})}</div>:<div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">{SOM_VISUAL_STYLES.map(style=>{const selected=designConfig.visualStyle===style.id;return <button key={style.id} onClick={()=>setVisualStyle(style.id)} className={`p-4 rounded-2xl border-2 text-left ${selected?'border-brand bg-brand-soft/20 shadow-md':'border-slate-200 dark:border-slate-800'}`}><div className="flex items-center justify-between"><span className="text-xs font-black text-slate-900 dark:text-white">{style.name}</span>{selected&&<span className="text-[10px] text-brand flex items-center gap-1"><Check size={12}/> กำลังใช้</span>}</div><p className="text-[11px] text-slate-500 dark:text-slate-400 mt-2">{style.description}</p></button>})}</div>}</div>
  <div className="p-4 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between bg-slate-50/50 dark:bg-slate-900/50"><span className="text-[11px] text-slate-400">ธีม: <strong className="text-brand uppercase">{designConfig.themeId}</strong> • สไตล์: <strong className="text-brand uppercase">{designConfig.visualStyle}</strong></span><button onClick={onClose} className="px-5 py-2 text-xs font-bold bg-slate-900 dark:bg-white text-white dark:text-slate-900 rounded-xl">เสร็จสิ้น</button></div>
 </motion.div></div></AnimatePresence>;
};
