import { useState, useEffect, useMemo, useRef } from 'react';
import { collection, query, orderBy, onSnapshot, addDoc, doc, deleteDoc, updateDoc, deleteField, setDoc, writeBatch } from 'firebase/firestore';
import { db, handleFirestoreError, OperationType } from '../lib/firebase';
import { Transaction } from '../types';
import { useAuth } from './useAuth';
import { logAuditEvent } from '../lib/auditLogger';
import { useNetworkStatus } from './useNetworkStatus';
import { toast } from 'react-hot-toast';
import { dbManager } from '../lib/dbManager';
function removeUndefinedFields<T>(obj: T): T { if (obj === null || obj === undefined || typeof obj !== 'object') return obj; if (Array.isArray(obj)) return obj.map(removeUndefinedFields) as unknown as T; return Object.fromEntries(Object.entries(obj as Record<string, any>).filter(([, value]) => value !== undefined).map(([key, value]) => [key, value && typeof value === 'object' ? removeUndefinedFields(value) : value])) as T; }
function prepareUpdateData(updates: Record<string, any>): Record<string, any> { const cleaned: Record<string, any> = {}; for (const [key, value] of Object.entries(updates)) cleaned[key] = value === undefined ? deleteField() : (value !== null && typeof value === 'object' && !Array.isArray(value) ? removeUndefinedFields(value) : value); return cleaned; }
function isRetryableFirestoreError(error: any): boolean { const code = String(error?.code || '').replace(/^firestore\//, ''); return ['unavailable', 'deadline-exceeded', 'aborted', 'internal', 'resource-exhausted'].includes(code) || /network|offline|failed to fetch|quota|temporarily unavailable/i.test(String(error?.message || '')); }
function mergeTransactions(offline: Transaction[], remote: Transaction[]) { const byId = new Map<string, Transaction>(); offline.forEach(item => { if (item.id) byId.set(String(item.id), item); }); remote.forEach(item => { if (item.id) byId.set(String(item.id), item); }); return [...byId.values()].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()); }
let offlineSyncPromise: Promise<void> | null = null; let offlineSyncCooldownUntil = 0;
export function useTransactions() {
 const [firestoreTransactions, setFirestoreTransactions] = useState<Transaction[]>([]); const [offlineQueue, setOfflineQueue] = useState<Transaction[]>(() => dbManager.readOfflineQueue<Transaction>()); const [loading, setLoading] = useState(true); const { user } = useAuth(); const isOnline = useNetworkStatus(); const isSyncingRef = useRef(false); const lastQuotaExhaustedRef = useRef<number>(0); const refreshOfflineQueue = () => setOfflineQueue(dbManager.readOfflineQueue<Transaction>());
 useEffect(() => { const refresh = () => refreshOfflineQueue(); window.addEventListener('solar_offline_queue_changed', refresh); return () => window.removeEventListener('solar_offline_queue_changed', refresh); }, []);
 useEffect(() => { if (!user) { setFirestoreTransactions([]); setLoading(false); return; } const q = query(collection(db, 'transactions'), orderBy('date', 'desc')); const unsubscribe = onSnapshot(q, { includeMetadataChanges: false }, snapshot => { setFirestoreTransactions(snapshot.docs.map(d => ({ id: d.id, ...d.data(), hasPendingWrites: d.metadata.hasPendingWrites })) as Transaction[]); setLoading(false); }, error => { console.error('Error fetching transactions:', error); handleFirestoreError(error, OperationType.LIST, 'transactions'); setLoading(false); }); return () => unsubscribe(); }, [user]);
 const transactions = useMemo(() => mergeTransactions(offlineQueue, firestoreTransactions), [firestoreTransactions, offlineQueue]);
 const syncOfflineQueue = async (): Promise<void> => { if (!isOnline || !user || isSyncingRef.current) return; if (offlineSyncPromise) return offlineSyncPromise; if (Date.now() <= Math.max(lastQuotaExhaustedRef.current, offlineSyncCooldownUntil)) return; offlineSyncPromise = (async () => { try { isSyncingRef.current = true; await dbManager.flushOfflineQueue(); refreshOfflineQueue(); } catch (error: any) { console.warn('Error syncing offline transaction queue:', error); if (isRetryableFirestoreError(error)) { const retryDelay = error?.code === 'resource-exhausted' ? 300000 : 30000; lastQuotaExhaustedRef.current = Date.now() + retryDelay; offlineSyncCooldownUntil = Date.now() + retryDelay; } else toast.error('ไม่สามารถซิงค์ออเดอร์ออฟไลน์ได้ เนื่องจากสิทธิ์หรือข้อมูลไม่ถูกต้อง กรุณาตรวจสอบแล้วลองใหม่', { id: 'offline-queue-sync-error' }); } finally { isSyncingRef.current = false; } })().finally(() => { offlineSyncPromise = null; }); return offlineSyncPromise; };
 useEffect(() => { if (isOnline && user && offlineQueue.length > 0 && Date.now() > Math.max(lastQuotaExhaustedRef.current, offlineSyncCooldownUntil)) void syncOfflineQueue(); }, [isOnline, user, offlineQueue.length]);
 const addTransaction = async (transaction: Omit<Transaction, 'id' | 'createdAt' | 'createdBy'>) => { if (!user) throw new Error('ต้องเข้าสู่ระบบก่อนสร้างรายการ'); const tempId = `offline_queued_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`; const cleanedData = removeUndefinedFields({ ...transaction, createdAt: new Date().toISOString(), createdBy: user.uid }); const queueOffline = () => { const offlineTx: Transaction = { id: tempId, ...cleanedData, hasPendingWrites: true }; setOfflineQueue(dbManager.enqueueOfflineTransaction(offlineTx)); toast.success('💾 จัดเก็บออฟไลน์เรียบร้อย! รายการจะซิงค์ขึ้นระบบคลาวด์อัตโนมัติเมื่ออินเทอร์เน็ตพร้อมใช้งาน', { id: 'offline-queued-success', icon: '📡', duration: 5000 }); return tempId; }; if (!isOnline || dbManager.getActualProvider() === 'local') return queueOffline(); try { const docRef = await addDoc(collection(db, 'transactions'), cleanedData); try { await logAuditEvent({ action: 'TRANSACTION_CREATE', category: 'transaction', targetId: docRef.id, targetName: `${transaction.detail || transaction.category} (฿${transaction.amount?.toLocaleString()})`, details: `สร้างรายการ ${transaction.type === 'income' ? 'รายรับ' : 'รายจ่าย'} หมวดหมู่ [${transaction.category}] รายละเอียด: \"${transaction.detail || '-'}\" จำนวน ฿${transaction.amount?.toLocaleString()}`, newData: cleanedData }); } catch (auditError) { console.error('Transaction created but audit log failed:', auditError); } return docRef.id; } catch (error: any) { console.error('Error adding transaction to Firestore:', error); if (isRetryableFirestoreError(error)) return queueOffline(); handleFirestoreError(error, OperationType.CREATE, 'transactions'); throw error; } };
 const deleteTransaction = async (id: string) => { if (id.startsWith('offline_queued_')) { setOfflineQueue(dbManager.removeOfflineQueueTransaction<Transaction>(id)); toast.success('ลบรายการที่ค้างคิวออฟไลน์เรียบร้อยแล้ว'); return; } try { const existingTx = transactions.find(t => t.id === id); await deleteDoc(doc(db, 'transactions', id)); await logAuditEvent({ action: 'TRANSACTION_DELETE', category: 'transaction', targetId: id, targetName: existingTx ? `${existingTx.detail || existingTx.category} (฿${existingTx.amount?.toLocaleString()})` : id, details: `ลบรายการธุรกรรม ${existingTx?.type === 'income' ? 'รายรับ' : 'รายจ่าย'}: \"${existingTx?.detail || existingTx?.category || id}\" ยอดเงิน ฿${existingTx?.amount?.toLocaleString() || 0}`, previousData: existingTx || null }); } catch (error) { console.error('Error deleting transaction:', error); throw error; } };
 const updateTransaction = async (id: string, updates: Partial<Omit<Transaction, 'id' | 'createdAt' | 'createdBy'>>) => { if (id.startsWith('offline_queued_')) { setOfflineQueue(dbManager.updateOfflineQueueTransaction<Transaction>(id, updates)); toast.success('แก้ไขรายการในคิวออฟไลน์เรียบร้อยแล้ว'); return; } try { const existingTx = transactions.find(t => t.id === id); await updateDoc(doc(db, 'transactions', id), prepareUpdateData(updates)); await logAuditEvent({ action: 'TRANSACTION_UPDATE', category: 'transaction', targetId: id, targetName: existingTx ? `${existingTx.detail || existingTx.category} (฿${existingTx.amount?.toLocaleString()})` : id, details: `แก้ไขข้อมูลรายการธุรกรรม \"${existingTx?.detail || existingTx?.category || id}\"`, previousData: existingTx || null, newData: updates }); } catch (error) { console.error('Error updating transaction:', error); throw error; } };
 const restoreTransaction = async (id: string, data: Transaction) => { try { const { id: _, ...rest } = data; await setDoc(doc(db, 'transactions', id), removeUndefinedFields(rest)); await logAuditEvent({ action: 'TRANSACTION_RESTORE', category: 'transaction', targetId: id, targetName: `${data.detail || data.category} (฿${data.amount?.toLocaleString()})`, details: `กู้คืนรายการที่ถูกลบไปแล้ว: \"${data.detail || data.category}\" ยอดเงิน ฿${data.amount?.toLocaleString()}`, newData: data }); } catch (error) { console.error('Error restoring transaction:', error); throw error; } };
 const deleteAllTransactions = async () => { try { const count = transactions.length; const persistedIds = transactions.map(tx => tx.id).filter((id): id is string => Boolean(id && !id.startsWith('offline_queued_'))); for (let start = 0; start < persistedIds.length; start += 450) { const batch = writeBatch(db); persistedIds.slice(start, start + 450).forEach(id => batch.delete(doc(db, 'transactions', id))); await batch.commit(); } dbManager.clearOfflineQueue(); setOfflineQueue([]); await logAuditEvent({ action: 'TRANSACTION_BATCH_DELETE', category: 'transaction', targetId: 'ALL', targetName: `ล้างข้อมูลธุรกรรมทั้งหมด ${count} รายการ`, details: `ลบรายการธุรกรรมทั้งหมดในระบบจำนวน ${count} รายการ (รวมถึงออฟไลน์คิว)` }); } catch (error) { console.error('Error deleting all transactions:', error); throw error; } };
 const pendingCount = transactions.filter(t => t.hasPendingWrites || t.id?.startsWith('offline_queued_')).length; return { transactions, loading, pendingCount, addTransaction, deleteTransaction, updateTransaction, restoreTransaction, deleteAllTransactions };
}
