import { useState } from 'react';
import { motion } from 'motion/react';
import { Sliders } from 'lucide-react';
import { BottomNavConfig, BottomNavItemConfig, TransactionType, TransactionCategory } from '../../types';
import { renderNavIcon } from './NavIconHelper';
import { BottomNavCustomizerModal } from './BottomNavCustomizerModal';
import { useAuth } from '../../hooks/useAuth';
import { getUserPermissions } from '../../utils/permissions';
import { useTheme } from '../../hooks/useTheme';
import { DEFAULT_BOTTOM_NAV_CONFIG } from '../../hooks/useAppConfig';
import toast from 'react-hot-toast';

interface BottomNavigationBarProps { activeTab:string; onNavigate:(tab:any)=>void; config?:BottomNavConfig; onUpdateConfig:(newConfig:BottomNavConfig)=>void; onResetDefaults:()=>void; onQuickAdd?:(type:TransactionType,category:TransactionCategory,detail?:string,amount?:number)=>void; onOpenQuickDesign?:()=>void; onLockApp?:()=>void; onSyncNow?:()=>void; }

export function BottomNavigationBar({activeTab,onNavigate,config=DEFAULT_BOTTOM_NAV_CONFIG,onUpdateConfig,onResetDefaults,onQuickAdd,onOpenQuickDesign,onLockApp,onSyncNow}:BottomNavigationBarProps){
 const [isCustomizerOpen,setIsCustomizerOpen]=useState(false); const {appUser,user}=useAuth(); const {toggleTheme}=useTheme(); const userPerms=getUserPermissions(appUser); const isAdminOrOwner=appUser?.role==='admin'||user?.email?.toLowerCase()==='b.b.thodsawat@gmail.com'; const currentRole=appUser?.role||(isAdminOrOwner?'admin':'viewer');
 const items=(config?.items||DEFAULT_BOTTOM_NAV_CONFIG.items).filter(i=>i.isActive&&(!i.allowedRoles?.length||isAdminOrOwner||i.allowedRoles.includes(currentRole)));
 const styleType=config?.styleType||'floating-capsule', activeIndicator=config?.activeIndicator||'pill', labelMode=config?.labelMode||'all', iconSize=config?.iconSize||'medium', showOnDesktop=config?.showOnDesktop||false; const iconPx=iconSize==='small'?18:iconSize==='large'?24:21;
 const handleItemClick=(item:BottomNavItemConfig)=>{ if(item.actionType==='tab'&&item.targetTab){ if(item.targetTab==='dashboard'&&!userPerms.canViewDashboard)return toast.error('คุณไม่มีสิทธิ์เข้าถึงหน้าแดชบอร์ด'); if(item.targetTab==='pos'&&!userPerms.canAddTransactions)return toast.error('คุณไม่มีสิทธิ์เข้าถึงระบบขาย POS'); if(item.targetTab==='reports'&&!userPerms.canViewReports)return toast.error('คุณไม่มีสิทธิ์เข้าถึงหน้ารายงาน'); if(item.targetTab==='audit_logs'&&!userPerms.canViewAuditLogs&&!isAdminOrOwner)return toast.error('คุณไม่มีสิทธิ์เข้าถึง Audit Logs'); if(item.targetTab==='users'&&!isAdminOrOwner&&appUser?.role!=='manager')return toast.error('คุณไม่มีสิทธิ์จัดการผู้ใช้งาน'); onNavigate(item.targetTab); return; } if(item.actionType!=='quick_action')return; switch(item.quickAction){case'quick_income':return userPerms.canAddTransactions?(onQuickAdd?onQuickAdd('income','รายรับจาก Sale order','รายรับด่วน'):onNavigate('pos')):toast.error('คุณไม่มีสิทธิ์เพิ่มรายการ'); case'quick_expense':return userPerms.canAddTransactions?(onQuickAdd?onQuickAdd('expense','ค่าใช้จ่ายอื่นๆ','รายจ่ายด่วน'):onNavigate('pos')):toast.error('คุณไม่มีสิทธิ์เพิ่มรายการ'); case'toggle_theme':return toggleTheme(); case'quick_design':return onOpenQuickDesign?onOpenQuickDesign():setIsCustomizerOpen(true); case'pin_lock':return onLockApp?onLockApp():toast('กำลังล็อคหน้าจอ...'); case'sync_now':return onSyncNow?onSyncNow():toast.success('เริ่มการซิงค์ข้อมูลคลาวด์'); case'customize_menu':return setIsCustomizerOpen(true); default:return;} };
 const getContainerStyle=()=>{switch(styleType){case'dock-modern':return'fixed bottom-2 left-3 right-3 max-w-lg mx-auto bg-white/92 dark:bg-slate-900/94 text-slate-700 dark:text-white backdrop-blur-2xl border border-slate-200/80 dark:border-slate-700/80 rounded-[24px] pb-safe shadow-[0_12px_40px_rgba(15,23,42,0.16)] z-40';case'glassmorphism':return'fixed bottom-2 left-3 right-3 max-w-lg mx-auto bg-white/78 dark:bg-slate-900/78 text-slate-700 dark:text-white backdrop-blur-2xl border border-white/70 dark:border-slate-700/70 rounded-[24px] pb-safe shadow-[0_12px_40px_rgba(15,23,42,0.14)] z-40';case'neon-glow':return'fixed bottom-2 left-3 right-3 max-w-lg mx-auto bg-slate-950 text-white border border-brand/40 rounded-[24px] pb-safe shadow-[0_10px_35px_rgba(59,130,246,0.18)] z-40';case'classic-edge':return'fixed bottom-0 left-0 right-0 bg-white/96 dark:bg-slate-950/96 text-slate-700 dark:text-white border-t border-slate-200 dark:border-slate-800 pb-safe shadow-[0_-8px_28px_rgba(15,23,42,0.08)] z-40';default:return'fixed bottom-2 left-3 right-3 max-w-lg mx-auto bg-slate-950/95 dark:bg-slate-900/96 text-white backdrop-blur-2xl border border-slate-800 rounded-[24px] pb-safe shadow-[0_12px_40px_rgba(15,23,42,0.28)] z-40';}};
 return <><nav aria-label="เมนูหลักบนมือถือ" className={`${getContainerStyle()} ${showOnDesktop?'block':'lg:hidden'} transition-all duration-300`}><div className="h-[68px] sm:h-[72px] px-2 sm:px-3 flex items-center gap-1"><div className="flex-1 grid grid-flow-col auto-cols-fr items-stretch gap-0.5 min-w-0">{items.slice(0,5).map(item=>{const isActive=item.actionType==='tab'&&activeTab===item.targetTab;return <button key={item.id} onClick={()=>handleItemClick(item)} aria-current={isActive?'page':undefined} aria-label={item.label} className={`relative min-w-0 flex flex-col items-center justify-center rounded-[18px] px-0.5 py-1.5 transition-all duration-200 active:scale-95 ${isActive?'text-brand dark:text-white':'text-slate-400 dark:text-slate-400'}`}>{isActive&&activeIndicator==='pill'&&<motion.div layoutId="activeBottomNavPill" className="absolute inset-0 bg-brand/10 dark:bg-brand/20 border border-brand/20 rounded-[18px]" transition={{type:'spring',stiffness:420,damping:32}}/>}<span className="relative z-10 flex h-8 w-8 items-center justify-center rounded-xl">{renderNavIcon(item.iconName,iconPx)}</span>{(labelMode==='all'||(labelMode==='active-only'&&isActive))&&<span className="relative z-10 mt-0.5 text-[9px] sm:text-[10px] font-bold leading-none truncate max-w-[68px]">{item.label}</span>}{item.badgeText&&<span className="absolute top-1 right-1 px-1 bg-rose-500 text-white rounded-full text-[7px] font-black">{item.badgeText}</span>}</button>})}</div><button onClick={()=>setIsCustomizerOpen(true)} aria-label="ปรับแต่งเมนู" title="ปรับแต่งเมนู" className="shrink-0 h-10 w-10 rounded-2xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-500 dark:text-slate-300 flex items-center justify-center active:scale-95 transition-transform"><Sliders size={17}/></button></div></nav><BottomNavCustomizerModal isOpen={isCustomizerOpen} onClose={()=>setIsCustomizerOpen(false)} config={config} onSaveConfig={onUpdateConfig} onResetDefaults={onResetDefaults}/></>;
}
