import React from 'react';
import { 
  LayoutDashboard, 
  BarChart3, 
  PieChart, 
  LineChart, 
  TrendingUp, 
  Sparkles, 
  Flame, 
  Activity,
  PlusCircle, 
  ShoppingCart, 
  DollarSign, 
  Wallet, 
  CreditCard, 
  Receipt, 
  ArrowDownLeft, 
  ArrowUpRight, 
  Banknote, 
  QrCode, 
  Calculator,
  ListOrdered, 
  History as HistoryIcon, 
  Clock, 
  FileText, 
  ClipboardList, 
  BookOpen, 
  Layers,
  UserCheck, 
  Users, 
  UserPlus, 
  HeartHandshake, 
  Phone, 
  Mail, 
  Contact,
  Calendar, 
  Wrench, 
  ShieldCheck, 
  Award, 
  Package, 
  Truck, 
  Hammer, 
  SunMedium, 
  Sun, 
  Zap,
  Settings, 
  Settings2, 
  Sliders, 
  Palette, 
  Lock, 
  KeyRound, 
  Shield, 
  Search, 
  Moon, 
  Bell, 
  HelpCircle,
  HelpCircle as DefaultIcon
} from 'lucide-react';

export const AVAILABLE_NAV_ICONS: { name: string; label: string; category: string; icon: React.ComponentType<{ size?: number; className?: string }> }[] = [
  // Dashboard & Metrics
  { name: 'LayoutDashboard', label: 'ภาพรวม Dashboard', category: 'ทั่วไป', icon: LayoutDashboard },
  { name: 'BarChart3', label: 'กราฟแท่ง', category: 'รายงาน & การเงิน', icon: BarChart3 },
  { name: 'PieChart', label: 'กราฟวงกลม', category: 'รายงาน & การเงิน', icon: PieChart },
  { name: 'LineChart', label: 'กราฟเส้น', category: 'รายงาน & การเงิน', icon: LineChart },
  { name: 'TrendingUp', label: 'แนวโน้มเติบโต', category: 'รายงาน & การเงิน', icon: TrendingUp },
  { name: 'Sparkles', label: 'AI ประกายแสง', category: 'ทั่วไป', icon: Sparkles },
  { name: 'Flame', label: 'ยอดฮิต ไฟแรง', category: 'ทั่วไป', icon: Flame },
  { name: 'Activity', label: 'ชีพจรธุรกิจ', category: 'ทั่วไป', icon: Activity },

  // POS & Transactions
  { name: 'PlusCircle', label: 'เพิ่มรายการ', category: 'ขาย & รายรับ-จ่าย', icon: PlusCircle },
  { name: 'ShoppingCart', label: 'ตะกร้าสินค้า', category: 'ขาย & รายรับ-จ่าย', icon: ShoppingCart },
  { name: 'DollarSign', label: 'ดอลลาร์/เงิน', category: 'ขาย & รายรับ-จ่าย', icon: DollarSign },
  { name: 'Wallet', label: 'กระเป๋าเงิน', category: 'ขาย & รายรับ-จ่าย', icon: Wallet },
  { name: 'Banknote', label: 'ธนบัตรเงินสด', category: 'ขาย & รายรับ-จ่าย', icon: Banknote },
  { name: 'CreditCard', label: 'บัตร/การโอน', category: 'ขาย & รายรับ-จ่าย', icon: CreditCard },
  { name: 'Receipt', label: 'ใบเสร็จรับเงิน', category: 'ขาย & รายรับ-จ่าย', icon: Receipt },
  { name: 'ArrowDownLeft', label: 'รายรับเข้า (+)', category: 'ขาย & รายรับ-จ่าย', icon: ArrowDownLeft },
  { name: 'ArrowUpRight', label: 'รายจ่ายออก (-)', category: 'ขาย & รายรับ-จ่าย', icon: ArrowUpRight },
  { name: 'QrCode', label: 'พร้อมเพย์ QR', category: 'ขาย & รายรับ-จ่าย', icon: QrCode },
  { name: 'Calculator', label: 'เครื่องคิดเลข', category: 'ขาย & รายรับ-จ่าย', icon: Calculator },

  // History & Docs
  { name: 'ListOrdered', label: 'รายการประวัติ', category: 'ประวัติ & บันทึก', icon: ListOrdered },
  { name: 'History', label: 'ย้อนหลัง', category: 'ประวัติ & บันทึก', icon: HistoryIcon },
  { name: 'Clock', label: 'เวลา & กิจกรรม', category: 'ประวัติ & บันทึก', icon: Clock },
  { name: 'FileText', label: 'เอกสาร/สัญญา', category: 'ประวัติ & บันทึก', icon: FileText },
  { name: 'ClipboardList', label: 'เช็กลิสต์', category: 'ประวัติ & บันทึก', icon: ClipboardList },
  { name: 'BookOpen', label: 'สมุดบันทึก', category: 'ประวัติ & บันทึก', icon: BookOpen },
  { name: 'Layers', label: 'หมวดหมู่', category: 'ประวัติ & บันทึก', icon: Layers },

  // Customers & People
  { name: 'UserCheck', label: 'ลูกค้า CRM', category: 'ลูกค้า & ผู้ใช้', icon: UserCheck },
  { name: 'Users', label: 'สมาชิก & ทีมงาน', category: 'ลูกค้า & ผู้ใช้', icon: Users },
  { name: 'UserPlus', label: 'เพิ่มลูกค้าใหม่', category: 'ลูกค้า & ผู้ใช้', icon: UserPlus },
  { name: 'HeartHandshake', label: 'ความสัมพันธ์ลูกค้า', category: 'ลูกค้า & ผู้ใช้', icon: HeartHandshake },
  { name: 'Phone', label: 'ติดต่อโทรศัพท์', category: 'ลูกค้า & ผู้ใช้', icon: Phone },
  { name: 'Mail', label: 'อีเมล', category: 'ลูกค้า & ผู้ใช้', icon: Mail },
  { name: 'Contact', label: 'สมุดผู้ติดต่อ', category: 'ลูกค้า & ผู้ใช้', icon: Contact },

  // Solar & Service & Hardware
  { name: 'Calendar', label: 'ปฏิทินนัดหมาย', category: 'บริการ & อุปกรณ์', icon: Calendar },
  { name: 'ShieldCheck', label: 'ใบรับประกันสินค้า', category: 'บริการ & อุปกรณ์', icon: ShieldCheck },
  { name: 'SunMedium', label: 'แผงโซล่าเซลล์', category: 'บริการ & อุปกรณ์', icon: SunMedium },
  { name: 'Sun', label: 'แสงอาทิตย์', category: 'บริการ & อุปกรณ์', icon: Sun },
  { name: 'Zap', label: 'กระแสไฟฟ้า/พลังงาน', category: 'บริการ & อุปกรณ์', icon: Zap },
  { name: 'Wrench', label: 'ช่างซ่อมบำรุง', category: 'บริการ & อุปกรณ์', icon: Wrench },
  { name: 'Hammer', label: 'งานติดตั้ง', category: 'บริการ & อุปกรณ์', icon: Hammer },
  { name: 'Package', label: 'พัสดุ & สต็อก', category: 'บริการ & อุปกรณ์', icon: Package },
  { name: 'Truck', label: 'ขนส่ง/ส่งของ', category: 'บริการ & อุปกรณ์', icon: Truck },
  { name: 'Award', label: 'มาตรฐานการันตี', category: 'บริการ & อุปกรณ์', icon: Award },

  // Settings & System
  { name: 'Settings', label: 'ฟันเฟืองตั้งค่า', category: 'ระบบ & เครื่องมือ', icon: Settings },
  { name: 'Settings2', label: 'แผงควบคุมระบบ', category: 'ระบบ & เครื่องมือ', icon: Settings2 },
  { name: 'Sliders', label: 'ปรับแต่งสเกล', category: 'ระบบ & เครื่องมือ', icon: Sliders },
  { name: 'Palette', label: 'สลับธีมสี', category: 'ระบบ & เครื่องมือ', icon: Palette },
  { name: 'Lock', label: 'ล็อคหน้าจอ PIN', category: 'ระบบ & เครื่องมือ', icon: Lock },
  { name: 'KeyRound', label: 'กุญแจความปลอดภัย', category: 'ระบบ & เครื่องมือ', icon: KeyRound },
  { name: 'Shield', label: 'ความปลอดภัยระบบ', category: 'ระบบ & เครื่องมือ', icon: Shield },
  { name: 'Search', label: 'ค้นหาด่วน', category: 'ระบบ & เครื่องมือ', icon: Search },
  { name: 'Moon', label: 'โหมดกลางคืน', category: 'ระบบ & เครื่องมือ', icon: Moon },
  { name: 'Bell', label: 'การแจ้งเตือน', category: 'ระบบ & เครื่องมือ', icon: Bell }
];

export const ICON_MAP: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
  LayoutDashboard,
  BarChart3,
  PieChart,
  LineChart,
  TrendingUp,
  Sparkles,
  Flame,
  Activity,
  PlusCircle,
  ShoppingCart,
  DollarSign,
  Wallet,
  CreditCard,
  Receipt,
  ArrowDownLeft,
  ArrowUpRight,
  Banknote,
  QrCode,
  Calculator,
  ListOrdered,
  History: HistoryIcon,
  Clock,
  FileText,
  ClipboardList,
  BookOpen,
  Layers,
  UserCheck,
  Users,
  UserPlus,
  HeartHandshake,
  Phone,
  Mail,
  Contact,
  Calendar,
  Wrench,
  ShieldCheck,
  Award,
  Package,
  Truck,
  Hammer,
  SunMedium,
  Sun,
  Zap,
  Settings,
  Settings2,
  Sliders,
  Palette,
  Lock,
  KeyRound,
  Shield,
  Search,
  Moon,
  Bell,
  HelpCircle
};

export function renderNavIcon(iconName: string, size = 20, className = ''): React.ReactNode {
  const Component = ICON_MAP[iconName] || DefaultIcon;
  return <Component size={size} className={className} />;
}
