import { useMemo, useState } from 'react';
import { ArrowRight, ShieldCheck, AlertCircle } from 'lucide-react';
import { Toaster, toast } from 'react-hot-toast';
import { signInWithGoogle } from '../lib/firebase';
import { SOM_AUTH_BUILD } from '../auth-build';

export default function Login(){
 const [busy,setBusy]=useState(false); const [errorMessage,setErrorMessage]=useState('');
 const dark=useMemo(()=>window.matchMedia?.('(prefers-color-scheme: dark)').matches??false,[]);
 const handleLogin=async()=>{if(busy)return;setBusy(true);setErrorMessage('');try{const {error}=await signInWithGoogle();if(error)throw error;toast.success('กำลังเข้าสู่ระบบ...')}catch(e:any){const code=String(e?.code||'');const raw=String(e?.message||'');const m=code==='auth/popup-blocked'?'เบราว์เซอร์บล็อกหน้าต่าง Google Login กรุณาอนุญาต Pop-up แล้วลองใหม่':code==='auth/unauthorized-domain'?'โดเมน Production ยังไม่ได้รับอนุญาตใน Firebase Authentication':raw||'Google Login ไม่สำเร็จ กรุณาลองใหม่อีกครั้ง';setErrorMessage(m);toast.error(m);setBusy(false)}};
 return <main data-auth-build={SOM_AUTH_BUILD} className={`min-h-[100svh] w-full overflow-x-hidden ${dark?'bg-[#0b0d12] text-white':'bg-[#f7f8fa] text-slate-900'}`}><Toaster position="top-center"/><div className="min-h-[100svh] w-full flex items-center justify-center px-4 py-6 sm:px-6"><div className="w-full max-w-[390px]"><section className="text-center mb-8 sm:mb-10"><p className="text-[10px] font-bold tracking-[0.28em] uppercase text-indigo-500">Solar Operations Management</p><h1 className="mt-3 text-[clamp(1.75rem,8vw,2.35rem)] leading-tight font-black tracking-tight">Solar Order Manager</h1><p className={`mt-2 text-sm ${dark?'text-slate-400':'text-slate-500'}`}>ระบบจัดการงานขายและการดำเนินงานโซล่า</p></section><section className={`w-full rounded-[28px] border p-5 sm:p-7 shadow-[0_20px_60px_rgba(15,23,42,.10)] ${dark?'bg-white/[0.055] border-white/10':'bg-white border-slate-200/80'}`}><div className="mb-6"><h2 className="text-xl font-black">เข้าสู่ระบบ</h2><p className={`mt-1.5 text-sm leading-relaxed ${dark?'text-slate-400':'text-slate-500'}`}>เข้าสู่ระบบด้วยบัญชี Google ของคุณ</p></div><button type="button" onClick={handleLogin} disabled={busy} className="w-full min-h-[56px] rounded-2xl bg-slate-900 dark:bg-white text-white dark:text-slate-950 px-4 py-4 font-extrabold flex items-center justify-center gap-3 shadow-sm transition-transform active:scale-[.98] disabled:opacity-60 touch-manipulation"><span className="w-7 h-7 rounded-full bg-white dark:bg-slate-100 text-slate-900 flex items-center justify-center font-black text-sm">G</span><span className="text-sm">{busy?'กำลังเชื่อมต่อ...':'เข้าสู่ระบบด้วย Google'}</span>{busy?<span className="w-5 h-5 rounded-full border-2 border-slate-400 border-t-transparent animate-spin"/>:<ArrowRight size={17}/>}</button>{errorMessage&&<div className="mt-4 rounded-2xl border border-rose-400/30 bg-rose-500/10 p-3.5 text-xs leading-relaxed text-rose-500 flex gap-2.5"><AlertCircle size={17} className="shrink-0"/><span>{errorMessage}</span></div>}<div className={`mt-5 rounded-2xl px-4 py-3.5 text-[11px] text-center leading-relaxed ${dark?'bg-white/[0.04] text-slate-400':'bg-slate-50 text-slate-500'}`}><ShieldCheck size={15} className="inline mr-1.5 text-emerald-500"/>การเข้าสู่ระบบปลอดภัยด้วย Firebase Authentication</div></section><footer className={`mt-7 text-center ${dark?'text-slate-500':'text-slate-400'}`}><p className="text-[9px] tracking-[0.24em] uppercase">Developed by</p><p className="mt-1 text-sm font-black tracking-wide text-indigo-500">BOY THODSAWAT</p></footer></div></div></main>;
}
