import { useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, ShieldCheck, Sparkles, SunMedium, Moon, Monitor, AlertCircle } from 'lucide-react';
import { Toaster, toast } from 'react-hot-toast';
import { motion } from 'motion/react';
import { signInWithGoogle } from '../lib/firebase';
import { SOM_AUTH_BUILD } from '../auth-build';

type Settings={theme_mode:'light'|'dark'|'system';layout_style:'split-left'|'split-right'|'centered';animation:'ambient'|'minimal'|'none';show_developer_credit:boolean;developer_credit_name:string;show_developer_credit_on_login:boolean;welcome_title:string;welcome_subtitle:string;};
const defaults:Settings={theme_mode:'dark',layout_style:'split-left',animation:'ambient',show_developer_credit:true,developer_credit_name:'BOY THODSAWAT',show_developer_credit_on_login:true,welcome_title:'ศูนย์ควบคุมระบบ',welcome_subtitle:'จัดการงานขาย ระบบโซล่า และการเงินของคุณได้ในที่เดียว'};

export default function Login(){
 const [s]=useState<Settings>(defaults); const [busy,setBusy]=useState(false); const [errorMessage,setErrorMessage]=useState('');
 const dark=useMemo(()=>s.theme_mode==='dark'||(s.theme_mode==='system'&&window.matchMedia?.('(prefers-color-scheme: dark)').matches),[s.theme_mode]);
 const surface=dark?'bg-slate-950 text-white':'bg-slate-50 text-slate-900'; const muted=dark?'text-slate-400':'text-slate-500'; const card=dark?'bg-white/[0.06] border-white/10':'bg-white/90 border-slate-200/80';
 const handleLogin=async()=>{if(busy)return;setBusy(true);setErrorMessage('');try{const {error}=await signInWithGoogle();if(error)throw error;toast.success('กำลังเชื่อมต่อ Google และเข้าสู่ระบบ...')}catch(e:any){const code=String(e?.code||'');const raw=String(e?.message||'');const m=code==='auth/popup-blocked'?'เบราว์เซอร์บล็อกหน้าต่าง Google Login กรุณาอนุญาต Pop-up แล้วลองใหม่':code==='auth/unauthorized-domain'?'โดเมน Production ยังไม่ได้รับอนุญาตใน Firebase Authentication':raw||'Google Login ไม่สำเร็จ กรุณาลองใหม่อีกครั้ง';setErrorMessage(m);toast.error(m);setBusy(false)}};
 const left=<section className="relative flex min-h-[330px] lg:min-h-screen flex-1 overflow-hidden bg-gradient-to-br from-indigo-600 via-violet-600 to-slate-950 text-white px-6 py-8 sm:p-12 lg:p-16"><div className="absolute -right-32 -top-32 w-96 h-96 rounded-full bg-cyan-300/15 blur-3xl"/><div className="absolute -left-24 -bottom-24 w-80 h-80 rounded-full bg-amber-300/10 blur-3xl"/><motion.div animate={s.animation==='ambient'?{y:[0,-10,0],scale:[1,1.02,1]}:{}} transition={{duration:7,repeat:Infinity,ease:'easeInOut'}} className="relative z-10 flex flex-col justify-between w-full"><div><div className="flex items-center gap-3"><img src="/logo.jpg" alt="SOM" className="w-12 h-12 sm:w-14 sm:h-14 rounded-2xl object-cover border border-white/20 shadow-2xl"/><div><p className="text-[9px] tracking-[0.24em] uppercase font-black text-white/60">Solar Operations Management</p><h1 className="text-lg sm:text-xl font-black">SOM • Solar Order Manager</h1></div></div><div className="mt-10 lg:mt-14 max-w-xl"><p className="text-xs font-black text-cyan-200 tracking-wide">SMART BUSINESS CONTROL</p><h2 className="mt-2 text-3xl sm:text-5xl lg:text-6xl font-black tracking-tight leading-[1.05]">{s.welcome_title}</h2><p className="mt-4 text-sm sm:text-lg text-white/70 max-w-lg leading-relaxed">{s.welcome_subtitle}</p></div></div><div className="mt-10 space-y-3"><div className="flex items-center gap-3 text-[11px] sm:text-xs font-bold text-white/75"><CheckCircle2 size={16} className="text-emerald-300"/> Firebase Authentication & Firestore</div><div className="flex items-center gap-3 text-[11px] sm:text-xs font-bold text-white/75"><CheckCircle2 size={16} className="text-emerald-300"/> Mobile-first • Modern • Secure</div></div></motion.div></section>;
 const form=<section className="flex items-center justify-center px-4 py-6 sm:p-8 lg:p-12 lg:w-[520px] xl:w-[580px]"><div className="w-full max-w-md"><div className="flex justify-end gap-1 mb-5 sm:mb-8">{[["light",SunMedium],["dark",Moon],["system",Monitor]].map(([id,Icon]:any)=><span key={id} title={id} className={`p-2 rounded-xl ${s.theme_mode===id?'bg-indigo-500 text-white':dark?'text-slate-500':'text-slate-400'}`}><Icon size={15}/></span>)}</div><div className={`rounded-[1.75rem] sm:rounded-[2rem] border backdrop-blur-xl p-5 sm:p-8 shadow-2xl ${card}`}><div className="mb-6 sm:mb-8"><div className={`w-11 h-11 rounded-2xl flex items-center justify-center mb-4 ${dark?'bg-white/10':'bg-indigo-50'}`}><Sparkles size={21} className="text-indigo-500"/></div><p className="text-[10px] font-black tracking-[0.25em] uppercase text-indigo-500">Welcome back</p><h3 className="mt-2 text-2xl font-black">เข้าสู่ระบบ</h3><p className={`mt-2 text-sm leading-relaxed ${muted}`}>ใช้บัญชี Google ของคุณเพื่อเข้าใช้งาน SOM</p></div><button type="button" onClick={handleLogin} disabled={busy} className="w-full min-h-14 rounded-2xl bg-white text-slate-950 py-4 px-5 font-black flex items-center justify-center gap-3 shadow-lg transition-all active:scale-[0.98] disabled:opacity-60 touch-manipulation"><span className="w-7 h-7 rounded-full bg-slate-100 flex items-center justify-center text-base font-black">G</span><span className="text-sm sm:text-base">{busy?'กำลังเชื่อมต่อ Google...':'เข้าสู่ระบบด้วย Google'}</span>{busy?<span className="w-5 h-5 rounded-full border-2 border-slate-300 border-t-slate-950 animate-spin"/>:<ArrowRight size={18}/>}</button>{errorMessage&&<div className="mt-4 rounded-2xl border border-rose-400/30 bg-rose-500/10 p-4 text-sm text-rose-500 flex gap-3"><AlertCircle size={18} className="shrink-0"/><span>{errorMessage}</span></div>}<div className={`mt-5 rounded-2xl p-4 text-xs text-center leading-relaxed ${dark?'bg-white/[0.04] text-slate-400':'bg-slate-100 text-slate-500'}`}>การเข้าสู่ระบบครั้งแรกจะสร้างโปรไฟล์ผู้ใช้ใน Firestore โดยอัตโนมัติ</div><div className={`mt-5 flex items-center justify-center gap-2 text-[10px] ${muted}`}><ShieldCheck size={14} className="text-emerald-500"/> Firebase Auth • Firestore</div><div className="mt-6 pt-5 border-t border-slate-200/10 text-center"><p className="text-[9px] uppercase tracking-[0.24em] text-slate-400">DEVELOPED BY</p><p className="mt-1.5 text-sm font-black tracking-wide text-indigo-500">BOY THODSAWAT</p></div></div></div></section>;
 return <main data-auth-build={SOM_AUTH_BUILD} className={`min-h-screen ${surface} overflow-hidden transition-colors`}><Toaster position="top-center"/><div className={`min-h-screen flex flex-col lg:flex-row ${s.layout_style==='split-right'?'lg:flex-row-reverse':''} ${s.layout_style==='centered'?'lg:items-center lg:justify-center':''}`}>{s.layout_style==='centered'?<div className="w-full max-w-xl">{form}</div>:<>{left}{form}</>}</div></main>;
}
