import React, { useEffect, useMemo, useState } from 'react';
import { doc, onSnapshot, setDoc } from 'firebase/firestore';
import { Building2, FileText, Landmark, MapPin, Save, ShieldCheck, Stamp, Upload, UserRound, Wallet } from 'lucide-react';
import { db, handleFirestoreError, OperationType } from '../lib/firebase';
import { useAuth } from '../hooks/useAuth';
import { notifyReaction } from '../utils/feedback';

interface BusinessProfile {
  shopName:string; companyNameTh:string; companyNameEn:string; taxId:string; branchName:string;
  phone:string; email:string; website:string; address:string; district:string; province:string; postalCode:string;
  logoUrl:string; receiptTitle:string; receiptFooter:string; invoicePrefix:string; receiptPrefix:string;
  nextInvoiceNumber:number; nextReceiptNumber:number; bankName:string; bankAccountName:string; bankAccountNumber:string;
  authorizedName:string; authorizedTitle:string; signatureUrl:string; stampUrl:string; updatedAt?:string; updatedBy?:string;
}
const DEFAULTS:BusinessProfile={shopName:'ร้านกลางนาโซล่าเซลล์',companyNameTh:'',companyNameEn:'',taxId:'',branchName:'สำนักงานใหญ่',phone:'',email:'',website:'',address:'',district:'',province:'',postalCode:'',logoUrl:'',receiptTitle:'ใบเสร็จรับเงิน / ใบรับเงิน',receiptFooter:'ขอบคุณที่ใช้บริการ',invoicePrefix:'INV-',receiptPrefix:'RC-',nextInvoiceNumber:1,nextReceiptNumber:1,bankName:'',bankAccountName:'',bankAccountNumber:'',authorizedName:'',authorizedTitle:'ผู้มีอำนาจลงนาม',signatureUrl:'',stampUrl:''};
const sections=[['business','ข้อมูลกิจการ',Building2],['contact','ติดต่อและที่อยู่',MapPin],['documents','เอกสารและเลขที่',FileText],['payment','บัญชีรับเงิน',Landmark],['branding','โลโก้และลายเซ็น',Stamp]] as const;
type Section=typeof sections[number][0];

export default function BusinessDocumentsHub(){
 const {user,appUser}=useAuth(); const isAdmin=user?.email?.toLowerCase()==='b.b.thodsawat@gmail.com'||appUser?.role==='admin'||appUser?.role==='owner';
 const [data,setData]=useState(DEFAULTS); const [active,setActive]=useState<Section>('business'); const [saving,setSaving]=useState(false); const [loaded,setLoaded]=useState(false);
 useEffect(()=>{if(!user)return; const ref=doc(db,'settings','businessProfile'); return onSnapshot(ref,s=>{setData({...DEFAULTS,...(s.exists()?s.data():{})} as BusinessProfile);setLoaded(true)},e=>{handleFirestoreError(e,OperationType.GET,'settings/businessProfile');setLoaded(true)})},[user]);
 const completion=useMemo(()=>{const keys:(keyof BusinessProfile)[]=['shopName','companyNameTh','phone','address','province','taxId'];return Math.round(keys.filter(k=>String(data[k]??'').trim()).length/keys.length*100)},[data]);
 const update=<K extends keyof BusinessProfile>(key:K,value:BusinessProfile[K])=>setData(p=>({...p,[key]:value}));
 const save=async()=>{if(!isAdmin)return notifyReaction('error','เฉพาะผู้ดูแลระบบหรือเจ้าของกิจการเท่านั้น');if(!data.shopName.trim())return notifyReaction('warning','กรุณาระบุชื่อร้านค้า');setSaving(true);try{await setDoc(doc(db,'settings','businessProfile'),{...data,updatedAt:new Date().toISOString(),updatedBy:user?.uid||''});notifyReaction('success','บันทึกข้อมูลธุรกิจและเอกสารเรียบร้อย')}catch(e){handleFirestoreError(e,OperationType.WRITE,'settings/businessProfile');notifyReaction('error','บันทึกไม่สำเร็จ กรุณาตรวจสอบสิทธิ์ Firestore')}finally{setSaving(false)}};
 const Field=({label,value,onChange,type='text'}:{label:string;value:string|number;onChange:(v:string)=>void;type?:string})=><label className="block space-y-1.5"><span className="text-[11px] font-black text-slate-500">{label}</span><input disabled={!isAdmin||saving} type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-900 outline-none focus:ring-2 focus:ring-brand/20 disabled:opacity-60"/></label>;
 if(!loaded)return <div className="rounded-[28px] bg-white border border-slate-200 p-8 text-sm font-bold text-slate-500">กำลังโหลดข้อมูลธุรกิจ...</div>;
 const header=(title:string,Icon:any)=><div className="flex items-center gap-3"><span className="rounded-2xl bg-brand-soft text-brand p-3"><Icon size={19}/></span><div><h3 className="text-base font-black">{title}</h3><p className="text-[11px] text-slate-400 font-semibold">ข้อมูลส่วนกลาง ใช้ร่วมกันทุกเอกสาร</p></div></div>;
 return <section className="rounded-[28px] border border-slate-200 bg-white shadow-sm overflow-hidden"><div className="p-5 sm:p-7 border-b border-slate-100"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="inline-flex items-center gap-2 rounded-full bg-brand-soft px-3 py-1 text-[10px] font-black text-brand"><ShieldCheck size={13}/> SINGLE SOURCE OF TRUTH</div><h2 className="mt-3 text-xl sm:text-2xl font-black">ข้อมูลธุรกิจและเอกสาร</h2><p className="mt-1 text-xs font-medium text-slate-500">รวมข้อมูลที่ใช้บนใบเสนอราคา ใบแจ้งหนี้ ใบเสร็จ และเอกสารธุรกิจไว้หน้าเดียว ไม่ต้องกรอกซ้ำ</p></div><div className="flex items-center gap-3"><div className="min-w-[130px]"><div className="flex justify-between text-[10px] font-black text-slate-400 mb-1"><span>ความครบถ้วน</span><span>{completion}%</span></div><div className="h-2 rounded-full bg-slate-100 overflow-hidden"><div className="h-full rounded-full bg-brand" style={{width:`${completion}%`}}/></div></div><button onClick={save} disabled={!isAdmin||saving} className="rounded-2xl bg-slate-900 text-white px-4 py-3 text-xs font-black flex items-center gap-2 disabled:opacity-50"><Save size={15}/>{saving?'กำลังบันทึก':'บันทึกทั้งหมด'}</button></div></div></div>
 <div className="grid lg:grid-cols-[230px_1fr] min-h-[560px]"><nav className="border-b lg:border-b-0 lg:border-r border-slate-100 p-3 bg-slate-50/70 flex lg:flex-col gap-1 overflow-x-auto">{sections.map(([id,label,Icon])=><button key={id} onClick={()=>setActive(id)} className={`shrink-0 flex items-center gap-3 rounded-2xl px-3 py-3 text-left ${active===id?'bg-slate-900 text-white shadow-sm':'text-slate-600 hover:bg-white'}`}><Icon size={17}/><span className="text-xs font-black whitespace-nowrap">{label}</span></button>)}</nav><div className="p-5 sm:p-7">
 {active==='business'&&<div className="space-y-5">{header('ข้อมูลกิจการ',Building2)}<div className="grid sm:grid-cols-2 gap-4"><Field label="ชื่อร้านค้า" value={data.shopName} onChange={v=>update('shopName',v)}/><Field label="ชื่อบริษัทภาษาไทย" value={data.companyNameTh} onChange={v=>update('companyNameTh',v)}/><Field label="ชื่อบริษัทภาษาอังกฤษ" value={data.companyNameEn} onChange={v=>update('companyNameEn',v)}/><Field label="เลขประจำตัวผู้เสียภาษี" value={data.taxId} onChange={v=>update('taxId',v)}/><Field label="สาขา" value={data.branchName} onChange={v=>update('branchName',v)}/><Field label="เว็บไซต์" value={data.website} onChange={v=>update('website',v)}/></div></div>}
 {active==='contact'&&<div className="space-y-5">{header('ติดต่อและที่อยู่',MapPin)}<div className="grid sm:grid-cols-2 gap-4"><Field label="เบอร์โทรศัพท์" value={data.phone} onChange={v=>update('phone',v)} type="tel"/><Field label="อีเมล" value={data.email} onChange={v=>update('email',v)} type="email"/><Field label="ที่อยู่" value={data.address} onChange={v=>update('address',v)}/><Field label="อำเภอ / เขต" value={data.district} onChange={v=>update('district',v)}/><Field label="จังหวัด" value={data.province} onChange={v=>update('province',v)}/><Field label="รหัสไปรษณีย์" value={data.postalCode} onChange={v=>update('postalCode',v)}/></div></div>}
 {active==='documents'&&<div className="space-y-5">{header('เอกสารและเลขที่อัตโนมัติ',FileText)}<div className="grid sm:grid-cols-2 gap-4"><Field label="หัวใบเสร็จ" value={data.receiptTitle} onChange={v=>update('receiptTitle',v)}/><Field label="ข้อความท้ายเอกสาร" value={data.receiptFooter} onChange={v=>update('receiptFooter',v)}/><Field label="Prefix ใบแจ้งหนี้" value={data.invoicePrefix} onChange={v=>update('invoicePrefix',v)}/><Field label="เลขถัดไป (ใบแจ้งหนี้)" value={data.nextInvoiceNumber} onChange={v=>update('nextInvoiceNumber',Number(v)||1)} type="number"/><Field label="Prefix ใบเสร็จ" value={data.receiptPrefix} onChange={v=>update('receiptPrefix',v)}/><Field label="เลขถัดไป (ใบเสร็จ)" value={data.nextReceiptNumber} onChange={v=>update('nextReceiptNumber',Number(v)||1)} type="number"/></div><div className="rounded-2xl bg-amber-50 border border-amber-200 p-4 text-xs font-semibold text-amber-800">เลขเอกสารเป็นค่ากลางสำหรับการออกเอกสารใหม่ เพื่อป้องกันการตั้งเลขซ้ำระหว่างโมดูล</div></div>}
 {active==='payment'&&<div className="space-y-5">{header('บัญชีรับเงิน',Landmark)}<div className="grid sm:grid-cols-2 gap-4"><Field label="ธนาคาร" value={data.bankName} onChange={v=>update('bankName',v)}/><Field label="ชื่อบัญชี" value={data.bankAccountName} onChange={v=>update('bankAccountName',v)}/><Field label="เลขที่บัญชี" value={data.bankAccountNumber} onChange={v=>update('bankAccountNumber',v)}/></div><div className="rounded-2xl bg-slate-50 border border-slate-200 p-4 text-xs text-slate-500 flex gap-2"><Wallet size={16}/>ข้อมูลบัญชีนี้ใช้เป็นข้อมูลอ้างอิงบนเอกสารและหน้าชำระเงิน ไม่เก็บข้อมูลบัตรหรือรหัสลับ</div></div>}
 {active==='branding'&&<div className="space-y-5">{header('โลโก้ ลายเซ็น และตราประทับ',Stamp)}<div className="grid sm:grid-cols-2 gap-4"><Field label="URL โลโก้" value={data.logoUrl} onChange={v=>update('logoUrl',v)}/><Field label="URL ลายเซ็น" value={data.signatureUrl} onChange={v=>update('signatureUrl',v)}/><Field label="URL ตราประทับ" value={data.stampUrl} onChange={v=>update('stampUrl',v)}/><Field label="ชื่อผู้มีอำนาจลงนาม" value={data.authorizedName} onChange={v=>update('authorizedName',v)}/><Field label="ตำแหน่ง" value={data.authorizedTitle} onChange={v=>update('authorizedTitle',v)}/></div><div className="rounded-2xl border border-dashed border-slate-300 p-4 text-xs font-semibold text-slate-500 flex items-center gap-2"><Upload size={16}/> เตรียมช่องสำหรับเชื่อม File Storage โดยไม่ต้องสร้างเมนูใหม่</div></div>}
 </div></div>{!isAdmin&&<div className="border-t border-amber-100 bg-amber-50 px-5 py-3 text-xs font-bold text-amber-800 flex items-center gap-2"><UserRound size={15}/> โหมดดูอย่างเดียว: เฉพาะเจ้าของ/ผู้ดูแลระบบที่แก้ไขข้อมูลธุรกิจได้</div>}</section>;
}
