import React, { useEffect, useMemo, useRef, useState } from 'react';
import { doc, onSnapshot, setDoc } from 'firebase/firestore';
import { Building2, Check, FileText, Hash, Landmark, LayoutTemplate, ListChecks, MapPin, Palette, Save, Search, ShieldCheck, Stamp, WandSparkles, X } from 'lucide-react';
import toast from 'react-hot-toast';
import { db, handleFirestoreError, OperationType } from '../lib/firebase';
import { useAuth } from '../hooks/useAuth';
import { THAI_GEO_CACHE_KEY, THAI_GEO_URL } from '../data/thailandLocations';

type BusinessProfile = {
  shopName:string; companyNameTh:string; companyNameEn:string; taxId:string; branchName:string;
  phone:string; email:string; website:string; address:string; district:string; province:string; subdistrict:string; postalCode:string;
  logoUrl:string; receiptTitle:string; receiptFooter:string; invoicePrefix:string; receiptPrefix:string;
  nextInvoiceNumber:number; nextReceiptNumber:number; bankName:string; bankAccountName:string; bankAccountNumber:string;
  authorizedName:string; authorizedTitle:string; signatureUrl:string; stampUrl:string; updatedAt?:string; updatedBy?:string;
};
type DocTemplate = { id:string; name:string; prefix:string; paper:'A4'|'A5'|'THERMAL'; enabled:boolean; accent:string; footer:string };
type DocumentCenter = {
  templates:DocTemplate[];
  numbering:Record<string,{prefix:string; next:number; pad:number}>;
  terms:{payment:string; shipping:string; warranty:string; returnPolicy:string; footer:string};
  automation:{quoteToOrder:boolean; paymentReceipt:boolean; shippingNote:boolean; installationHandover:boolean; warrantyCertificate:boolean};
  archive:Array<{id:string; type:string; number:string; customer:string; orderId?:string; status:string; createdAt:string}>;
  updatedAt?:string; updatedBy?:string;
};
type Section='business'|'branding'|'templates'|'numbering'|'workflow'|'archive';
type Geo={name_th:string; districts:{name_th:string; sub_districts:{name_th:string; zip_code:number|string}[]}[]};

const BUSINESS_KEY='som:business-profile:v2';
const DOCUMENT_KEY='som:document-center:v2';
const DEFAULTS:BusinessProfile={shopName:'Solar order manager',companyNameTh:'โซล่าออเดอร์ เมเนเจอร์',companyNameEn:'Solar order manager',taxId:'',branchName:'สำนักงานใหญ่',phone:'',email:'',website:'',address:'',district:'',province:'',subdistrict:'',postalCode:'',logoUrl:'',receiptTitle:'ใบเสร็จรับเงิน / ใบรับเงิน',receiptFooter:'ขอบคุณที่ใช้บริการ',invoicePrefix:'INV-',receiptPrefix:'RC-',nextInvoiceNumber:1,nextReceiptNumber:1,bankName:'',bankAccountName:'',bankAccountNumber:'',authorizedName:'',authorizedTitle:'ผู้มีอำนาจลงนาม',signatureUrl:'',stampUrl:''};
const TEMPLATE_DEFAULTS:DocTemplate[]=[
  {id:'quote',name:'ใบเสนอราคา',prefix:'QT-',paper:'A4',enabled:true,accent:'brand',footer:'ใบเสนอราคานี้มีอายุ 7 วัน'},
  {id:'order',name:'ใบสั่งซื้อ',prefix:'SO-',paper:'A4',enabled:true,accent:'brand',footer:'เอกสารยืนยันรายการสั่งซื้อ'},
  {id:'invoice',name:'ใบแจ้งหนี้',prefix:'INV-',paper:'A4',enabled:true,accent:'brand',footer:'กรุณาชำระตามเงื่อนไขที่ระบุ'},
  {id:'receipt',name:'ใบเสร็จรับเงิน',prefix:'RC-',paper:'A4',enabled:true,accent:'emerald',footer:'ขอบคุณที่ใช้บริการ'},
  {id:'delivery',name:'ใบส่งสินค้า / ส่งมอบ',prefix:'DO-',paper:'A4',enabled:true,accent:'blue',footer:'ตรวจสอบสินค้าและลงชื่อรับมอบ'},
  {id:'installation',name:'ใบตรวจรับงานติดตั้ง',prefix:'INS-',paper:'A4',enabled:true,accent:'violet',footer:'ยืนยันการตรวจรับงาน'},
  {id:'warranty',name:'ใบรับประกัน',prefix:'WAR-',paper:'A4',enabled:true,accent:'amber',footer:'เงื่อนไขรับประกันตามเอกสารแนบท้าย'}
];
const DOCUMENT_DEFAULTS:DocumentCenter={templates:TEMPLATE_DEFAULTS,numbering:{quote:{prefix:'QT-',next:1,pad:5},order:{prefix:'SO-',next:1,pad:5},invoice:{prefix:'INV-',next:1,pad:5},receipt:{prefix:'RC-',next:1,pad:5},delivery:{prefix:'DO-',next:1,pad:5},installation:{prefix:'INS-',next:1,pad:5},warranty:{prefix:'WAR-',next:1,pad:5}},terms:{payment:'ชำระตามเงื่อนไขที่ระบุในใบเสนอราคาและใบสั่งซื้อ',shipping:'จัดส่งตามรอบและพื้นที่ที่ตกลงกับลูกค้า',warranty:'รับประกันตามเงื่อนไขของสินค้าและเอกสารรับประกัน',returnPolicy:'การเปลี่ยนหรือคืนสินค้าเป็นไปตามเงื่อนไขของบริษัท',footer:'ขอบคุณที่ไว้วางใจ Solar order manager'},automation:{quoteToOrder:true,paymentReceipt:true,shippingNote:true,installationHandover:true,warrantyCertificate:true},archive:[]};

function readLocal<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function writeLocal(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function mergeBusiness(v:any):BusinessProfile{return {...DEFAULTS,...(v||{})}}
function mergeDocuments(v:any):DocumentCenter{return {...DOCUMENT_DEFAULTS,...(v||{}),templates:Array.isArray(v?.templates)?v.templates:TEMPLATE_DEFAULTS,numbering:{...DOCUMENT_DEFAULTS.numbering,...(v?.numbering||{})},terms:{...DOCUMENT_DEFAULTS.terms,...(v?.terms||{})},automation:{...DOCUMENT_DEFAULTS.automation,...(v?.automation||{})},archive:Array.isArray(v?.archive)?v.archive:[]}}

export default function BusinessDocumentsHub(){
 const {user,appUser}=useAuth();
 const isAdmin=user?.email?.toLowerCase()==='b.b.thodsawat@gmail.com'||appUser?.role==='admin'||appUser?.role==='owner';
 const [business,setBusiness]=useState<BusinessProfile>(()=>readLocal(BUSINESS_KEY,DEFAULTS));
 const [documents,setDocuments]=useState<DocumentCenter>(()=>readLocal(DOCUMENT_KEY,DOCUMENT_DEFAULTS));
 const [section,setSection]=useState<Section>('business');
 const [loaded,setLoaded]=useState(false); const [saving,setSaving]=useState<'business'|'documents'|null>(null); const [query,setQuery]=useState('');
 const [geo,setGeo]=useState<Geo[]>([]); const [geoLoading,setGeoLoading]=useState(false); const [geoError,setGeoError]=useState(false);
 const alive=useRef(true);
 useEffect(()=>()=>{alive.current=false},[]);
 useEffect(()=>{if(!user||!db)return; const unsubBusiness=onSnapshot(doc(db,'settings','businessProfile'),s=>{if(!alive.current)return;const next=mergeBusiness(s.exists()?s.data():readLocal(BUSINESS_KEY,DEFAULTS));setBusiness(next);writeLocal(BUSINESS_KEY,next);setLoaded(true)},e=>{handleFirestoreError(e,OperationType.GET,'settings/businessProfile');setLoaded(true)});const unsubDocs=onSnapshot(doc(db,'settings','documentCenter'),s=>{if(!alive.current)return;const next=mergeDocuments(s.exists()?s.data():readLocal(DOCUMENT_KEY,DOCUMENT_DEFAULTS));setDocuments(next);writeLocal(DOCUMENT_KEY,next)},e=>handleFirestoreError(e,OperationType.GET,'settings/documentCenter'));return()=>{unsubBusiness();unsubDocs()}},[user]);
 useEffect(()=>{let cancelled=false;(async()=>{setGeoLoading(true);try{const cached=localStorage.getItem(THAI_GEO_CACHE_KEY);if(cached){const parsed=JSON.parse(cached);if(Array.isArray(parsed))setGeo(parsed)}const res=await fetch(THAI_GEO_URL,{cache:'force-cache'});if(!res.ok)throw new Error();const json=await res.json();if(!cancelled&&Array.isArray(json)){setGeo(json);localStorage.setItem(THAI_GEO_CACHE_KEY,JSON.stringify(json))}}catch{if(!cancelled&&!geo.length)setGeoError(true)}finally{if(!cancelled)setGeoLoading(false)}})();return()=>{cancelled=true}},[]);
 const provinces=useMemo(()=>geo.map(x=>x.name_th).filter(Boolean),[geo]); const province=useMemo(()=>geo.find(x=>x.name_th===business.province),[geo,business.province]); const districts=province?.districts?.map(x=>x.name_th).filter(Boolean)??[]; const district=province?.districts?.find(x=>x.name_th===business.district); const subdistricts=district?.sub_districts?.map(x=>x.name_th).filter(Boolean)??[];
 const completion=useMemo(()=>{const fields=['shopName','companyNameTh','companyNameEn','phone','address','province','district','subdistrict','postalCode','taxId'];return Math.round(fields.filter(k=>String((business as any)[k]??'').trim()).length/fields.length*100)},[business]);
 const saveBusiness=()=>{if(!isAdmin||saving)return;const required:[keyof BusinessProfile,string][]=[['shopName','ชื่อร้านค้า'],['companyNameTh','ชื่อบริษัทภาษาไทย'],['companyNameEn','ชื่อบริษัทภาษาอังกฤษ']];const missing=required.find(([k])=>!String(business[k]??'').trim());if(missing)return toast.error(`กรุณากรอก${missing[1]}`);const snapshot={...business,updatedAt:new Date().toISOString(),updatedBy:user?.uid||''};writeLocal(BUSINESS_KEY,snapshot);setBusiness(snapshot);setSaving('business');toast.success('บันทึกข้อมูลธุรกิจแล้ว');void setDoc(doc(db,'settings','businessProfile'),snapshot,{merge:true}).then(()=>{if(alive.current)toast.success('ซิงก์ข้อมูลธุรกิจสำเร็จ')}).catch(e=>{handleFirestoreError(e,OperationType.WRITE,'settings/businessProfile');if(alive.current)toast.error('ซิงก์ข้อมูลธุรกิจไม่สำเร็จ — ข้อมูลในเครื่องยังคงอยู่')}).finally(()=>alive.current&&setSaving(null))};
 const saveDocuments=()=>{if(!isAdmin||saving)return;const snapshot={...documents,updatedAt:new Date().toISOString(),updatedBy:user?.uid||''};writeLocal(DOCUMENT_KEY,snapshot);setDocuments(snapshot);setSaving('documents');toast.success('บันทึกการตั้งค่าเอกสารแล้ว');void setDoc(doc(db,'settings','documentCenter'),snapshot,{merge:true}).then(()=>{if(alive.current)toast.success('ซิงก์การตั้งค่าเอกสารสำเร็จ')}).catch(e=>{handleFirestoreError(e,OperationType.WRITE,'settings/documentCenter');if(alive.current)toast.error('ซิงก์เอกสารไม่สำเร็จ — ข้อมูลในเครื่องยังคงอยู่')}).finally(()=>alive.current&&setSaving(null))};
 const updateBusiness=<K extends keyof BusinessProfile>(key:K,value:BusinessProfile[K])=>setBusiness(v=>({...v,[key]:value}));
 const chooseProvince=(v:string)=>setBusiness(v0=>({...v0,province:v,district:'',subdistrict:'',postalCode:''})); const chooseDistrict=(v:string)=>setBusiness(v0=>({...v0,district:v,subdistrict:'',postalCode:''})); const chooseSubdistrict=(v:string)=>{const item=district?.sub_districts?.find(x=>x.name_th===v);setBusiness(v0=>({...v0,subdistrict:v,postalCode:item?.zip_code?String(item.zip_code):''}))};
 const updateTemplate=(id:string,patch:Partial<DocTemplate>)=>setDocuments(v=>({...v,templates:v.templates.map(t=>t.id===id?{...t,...patch}:t)}));
 const updateNumbering=(id:string,patch:Partial<{prefix:string;next:number;pad:number}>)=>setDocuments(v=>({...v,numbering:{...v.numbering,[id]:{...v.numbering[id],...patch}}}));
 const updateTerms=(key:keyof DocumentCenter['terms'],value:string)=>setDocuments(v=>({...v,terms:{...v.terms,[key]:value}})); const updateAutomation=(key:keyof DocumentCenter['automation'],value:boolean)=>setDocuments(v=>({...v,automation:{...v.automation,[key]:value}}));
 const archive=useMemo(()=>documents.archive.filter(x=>!query.trim()||`${x.number} ${x.customer} ${x.type} ${x.orderId||''}`.toLowerCase().includes(query.toLowerCase())),[documents.archive,query]);
 if(!loaded)return <div className="rounded-[28px] border border-slate-200 bg-white p-8 text-sm font-bold text-slate-500">กำลังโหลดข้อมูลธุรกิจและเอกสาร…</div>;
 const nav:[Section,string,any,string][]=[['business','ข้อมูลธุรกิจ',Building2,'ข้อมูลบริษัทและที่อยู่'],['branding','แบรนด์และการชำระเงิน',Palette,'โลโก้ บัญชี และลายเซ็น'],['templates','Template Designer',LayoutTemplate,'รูปแบบเอกสารและ Preview'],['numbering','เลขที่เอกสาร',Hash,'Prefix และ Running Number'],['workflow','Document Workflow',ListChecks,'สร้างเอกสารอัตโนมัติ'],['archive','Document Archive',FileText,'ค้นหาและตรวจสอบเอกสาร']];
 const Input=({label,value,onChange,placeholder='',type='text'}:{label:string;value:any;onChange:(v:string)=>void;placeholder?:string;type?:string})=><label className="block"><span className="mb-1.5 block text-[10px] font-black text-slate-500">{label}</span><input disabled={!isAdmin||saving!==null} type={type} value={value??''} placeholder={placeholder} onChange={e=>onChange(e.target.value)} className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-xs font-bold outline-none focus:ring-2 focus:ring-brand/20 disabled:opacity-60"/></label>;
 const TextArea=({label,value,onChange,rows=4}:{label:string;value:string;onChange:(v:string)=>void;rows?:number})=><label className="block"><span className="mb-1.5 block text-[10px] font-black text-slate-500">{label}</span><textarea disabled={!isAdmin||saving!==null} value={value} rows={rows} onChange={e=>onChange(e.target.value)} className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-xs font-bold outline-none focus:ring-2 focus:ring-brand/20 disabled:opacity-60 resize-y"/></label>;
 const Select=({label,value,options,onChange,disabled=false}:{label:string;value:string;options:string[];onChange:(v:string)=>void;disabled?:boolean})=><label className="block"><span className="mb-1.5 block text-[10px] font-black text-slate-500">{label}</span><select disabled={!isAdmin||saving!==null||disabled} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-xs font-bold disabled:opacity-60"><option value="">เลือก</option>{options.map(x=><option key={x}>{x}</option>)}</select></label>;
 const Toggle=({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void})=><button type="button" disabled={!isAdmin||saving!==null} onClick={()=>onChange(!checked)} className="flex w-full items-center justify-between rounded-2xl border border-slate-200 px-4 py-3 text-left disabled:opacity-60"><span className="text-xs font-bold">{label}</span><span className={`h-6 w-11 rounded-full p-1 transition ${checked?'bg-emerald-500':'bg-slate-300'}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${checked?'translate-x-5':''}`}/></span></button>;
 return <section className="overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><header className="border-b border-slate-100 p-5 sm:p-7"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-brand-soft px-3 py-1 text-[10px] font-black text-brand"><ShieldCheck size={13}/> BUSINESS CONTROL PLANE</div><h2 className="mt-3 text-xl sm:text-2xl font-black">ข้อมูลธุรกิจและเอกสาร</h2><p className="mt-1 max-w-3xl text-xs font-medium text-slate-500">แหล่งข้อมูลกลางสำหรับ POS, Order, Payment, Delivery, Installation และเอกสารทั้งหมด ลดการกรอกข้อมูลซ้ำ</p></div><div className="flex flex-wrap items-center gap-2"><div className="rounded-2xl bg-slate-50 px-4 py-2.5"><div className="text-[9px] font-black text-slate-400">BUSINESS PROFILE</div><div className="text-sm font-black">{completion}% ครบ</div></div><div className="rounded-2xl bg-slate-50 px-4 py-2.5"><div className="text-[9px] font-black text-slate-400">TEMPLATES</div><div className="text-sm font-black">{documents.templates.filter(x=>x.enabled).length}/{documents.templates.length}</div></div></div></div></header><div className="grid lg:grid-cols-[235px_1fr]"><nav className="flex gap-1 overflow-x-auto border-b border-slate-100 bg-slate-50/70 p-3 lg:flex-col lg:border-b-0 lg:border-r">{nav.map(([id,label,Icon,desc])=><button key={id} onClick={()=>setSection(id)} className={`min-w-max rounded-2xl p-3 text-left ${section===id?'bg-slate-900 text-white shadow-sm dark:bg-white dark:text-slate-900':'text-slate-600 hover:bg-white'}`}><div className="flex items-center gap-3"><Icon size={17}/><div><div className="text-xs font-black">{label}</div><div className={`text-[9px] ${section===id?'opacity-60':'text-slate-400'}`}>{desc}</div></div></div></button>)}</nav><main className="min-w-0 p-5 sm:p-7">
 {section==='business'&&<div className="space-y-5"><PanelTitle icon={Building2} title="ข้อมูลธุรกิจ" desc="ข้อมูลบริษัทและที่อยู่ที่ทุกเอกสารเรียกใช้ร่วมกัน"/><div className="grid gap-4 sm:grid-cols-2"><Input label="ชื่อร้านค้า" value={business.shopName} onChange={v=>updateBusiness('shopName',v)} placeholder="Solar order manager"/><Input label="ชื่อบริษัทภาษาไทย" value={business.companyNameTh} onChange={v=>updateBusiness('companyNameTh',v)}/><Input label="ชื่อบริษัทภาษาอังกฤษ" value={business.companyNameEn} onChange={v=>updateBusiness('companyNameEn',v)}/><Input label="เลขประจำตัวผู้เสียภาษี" value={business.taxId} onChange={v=>updateBusiness('taxId',v)}/><Input label="สาขา" value={business.branchName} onChange={v=>updateBusiness('branchName',v)}/><Input label="เว็บไซต์" value={business.website} onChange={v=>updateBusiness('website',v)}/><Input label="เบอร์โทรศัพท์" value={business.phone} onChange={v=>updateBusiness('phone',v)} type="tel"/><Input label="อีเมล" value={business.email} onChange={v=>updateBusiness('email',v)} type="email"/><div className="sm:col-span-2"><Input label="ที่อยู่" value={business.address} onChange={v=>updateBusiness('address',v)}/></div><Select label="จังหวัด" value={business.province} options={provinces} onChange={chooseProvince} disabled={geoLoading}/><Select label="อำเภอ / เขต" value={business.district} options={districts} onChange={chooseDistrict} disabled={!business.province}/><Select label="ตำบล / แขวง" value={business.subdistrict} options={subdistricts} onChange={chooseSubdistrict} disabled={!business.district}/><Input label="รหัสไปรษณีย์" value={business.postalCode} onChange={()=>undefined} placeholder="เติมอัตโนมัติ"/></div>{geoError&&<div className="rounded-2xl bg-amber-50 p-3 text-xs font-bold text-amber-700">ข้อมูลจังหวัดไม่พร้อมใช้งาน — สามารถกรอกข้อมูลพื้นฐานต่อได้</div>}<SaveBar saving={saving==='business'} onSave={saveBusiness}/></div>}
 {section==='branding'&&<div className="space-y-5"><PanelTitle icon={Palette} title="แบรนด์และการชำระเงิน" desc="ข้อมูลสำหรับ Header, Footer, ใบเสร็จ และบัญชีรับเงิน"/><div className="grid gap-4 sm:grid-cols-2"><Input label="Logo URL" value={business.logoUrl} onChange={v=>updateBusiness('logoUrl',v)} placeholder="https://..."/><Input label="หัวข้อใบเสร็จ" value={business.receiptTitle} onChange={v=>updateBusiness('receiptTitle',v)}/><Input label="ชื่อธนาคาร" value={business.bankName} onChange={v=>updateBusiness('bankName',v)}/><Input label="ชื่อบัญชี" value={business.bankAccountName} onChange={v=>updateBusiness('bankAccountName',v)}/><Input label="เลขบัญชี" value={business.bankAccountNumber} onChange={v=>updateBusiness('bankAccountNumber',v)}/><Input label="ชื่อผู้มีอำนาจลงนาม" value={business.authorizedName} onChange={v=>updateBusiness('authorizedName',v)}/><Input label="ตำแหน่ง" value={business.authorizedTitle} onChange={v=>updateBusiness('authorizedTitle',v)}/><Input label="Signature URL" value={business.signatureUrl} onChange={v=>updateBusiness('signatureUrl',v)}/><Input label="Stamp URL" value={business.stampUrl} onChange={v=>updateBusiness('stampUrl',v)}/><div className="sm:col-span-2"><TextArea label="ข้อความท้ายใบเสร็จ" value={business.receiptFooter} onChange={v=>updateBusiness('receiptFooter',v)}/></div></div><SaveBar saving={saving==='business'} onSave={saveBusiness}/></div>}
 {section==='templates'&&<div className="space-y-5"><PanelTitle icon={LayoutTemplate} title="Document Template Designer" desc="ตั้งค่ารูปแบบเอกสารกลาง พร้อม Preview แบบทันที"/><div className="grid gap-4 xl:grid-cols-2">{documents.templates.map(t=><div key={t.id} className={`rounded-[24px] border p-4 ${t.enabled?'border-slate-200':'border-dashed border-slate-300 opacity-60'}`}><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-black">{t.name}</div><div className="mt-1 text-[10px] text-slate-400">{t.prefix} • {t.paper}</div></div><Toggle label="ใช้งาน" checked={t.enabled} onChange={v=>updateTemplate(t.id,{enabled:v})}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Input label="Prefix" value={t.prefix} onChange={v=>updateTemplate(t.id,{prefix:v})}/><Select label="กระดาษ" value={t.paper} options={['A4','A5','THERMAL']} onChange={v=>updateTemplate(t.id,{paper:v as DocTemplate['paper']})}/><Select label="Accent" value={t.accent} options={['brand','emerald','blue','violet','amber']} onChange={v=>updateTemplate(t.id,{accent:v})}/><Input label="ข้อความท้ายเอกสาร" value={t.footer} onChange={v=>updateTemplate(t.id,{footer:v})}/></div><div className="mt-3 rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-4"><div className="mb-2 text-[9px] font-black text-slate-400">PREVIEW</div><div className="flex items-center justify-between border-b border-slate-200 pb-2"><span className="font-black">{business.companyNameTh}</span><span className="text-[9px] text-slate-400">{t.prefix}00001</span></div><div className="py-4 text-center text-xs font-black">{t.name}</div><div className="h-12 rounded bg-white"/><div className="mt-2 text-[9px] text-slate-400">{t.footer||documents.terms.footer}</div></div></div>)}</div><SaveBar saving={saving==='documents'} onSave={saveDocuments}/></div>}
 {section==='numbering'&&<div className="space-y-5"><PanelTitle icon={Hash} title="เลขที่เอกสาร" desc="กำหนด Prefix, Running Number และจำนวนหลักจากจุดเดียว"/><div className="grid gap-3 sm:grid-cols-2">{documents.templates.map(t=>{const n=documents.numbering[t.id]||{prefix:t.prefix,next:1,pad:5};return <div key={t.id} className="rounded-[24px] border border-slate-200 p-4"><div className="text-sm font-black">{t.name}</div><div className="mt-3 grid grid-cols-3 gap-2"><Input label="Prefix" value={n.prefix} onChange={v=>updateNumbering(t.id,{prefix:v})}/><Input label="เลขถัดไป" value={n.next} type="number" onChange={v=>updateNumbering(t.id,{next:Math.max(1,Number(v)||1)})}/><Input label="จำนวนหลัก" value={n.pad} type="number" onChange={v=>updateNumbering(t.id,{pad:Math.min(10,Math.max(1,Number(v)||1))})}/></div><div className="mt-3 rounded-xl bg-slate-50 px-3 py-2 text-xs font-black">ตัวอย่าง: {n.prefix}{String(n.next).padStart(n.pad,'0')}</div></div>})}</div><div className="rounded-2xl bg-blue-50 p-4 text-xs font-bold text-blue-700">ระบบควรออกเลขจาก Order เดิมเพียงครั้งเดียว และนำเลขเดียวกันไปผูกกับเอกสารที่เกี่ยวข้อง เพื่อป้องกันเลขซ้ำและข้อมูลไม่ตรงกัน</div><SaveBar saving={saving==='documents'} onSave={saveDocuments}/></div>}
 {section==='workflow'&&<div className="space-y-5"><PanelTitle icon={WandSparkles} title="Document Workflow" desc="ให้เอกสารเกิดจากเหตุการณ์ทางธุรกิจ โดยไม่ต้องกรอกข้อมูลซ้ำ"/><div className="space-y-3"><Toggle label="ยืนยัน Quote → สร้าง Order อัตโนมัติ" checked={documents.automation.quoteToOrder} onChange={v=>updateAutomation('quoteToOrder',v)}/><Toggle label="ชำระเงินสำเร็จ → สร้างใบเสร็จอัตโนมัติ" checked={documents.automation.paymentReceipt} onChange={v=>updateAutomation('paymentReceipt',v)}/><Toggle label="จัดส่ง → สร้างใบส่งสินค้า / ส่งมอบ" checked={documents.automation.shippingNote} onChange={v=>updateAutomation('shippingNote',v)}/><Toggle label="ติดตั้งเสร็จ → สร้างใบตรวจรับงาน" checked={documents.automation.installationHandover} onChange={v=>updateAutomation('installationHandover',v)}/><Toggle label="ติดตั้งเสร็จ → สร้างใบรับประกัน" checked={documents.automation.warrantyCertificate} onChange={v=>updateAutomation('warrantyCertificate',v)}/></div><div className="grid gap-4 lg:grid-cols-2"><TextArea label="เงื่อนไขการชำระเงิน" value={documents.terms.payment} onChange={v=>updateTerms('payment',v)}/><TextArea label="เงื่อนไขการจัดส่ง" value={documents.terms.shipping} onChange={v=>updateTerms('shipping',v)}/><TextArea label="เงื่อนไขรับประกัน" value={documents.terms.warranty} onChange={v=>updateTerms('warranty',v)}/><TextArea label="เงื่อนไขคืนสินค้า" value={documents.terms.returnPolicy} onChange={v=>updateTerms('returnPolicy',v)}/><div className="lg:col-span-2"><TextArea label="Footer กลางของเอกสาร" value={documents.terms.footer} onChange={v=>updateTerms('footer',v)}/></div></div><SaveBar saving={saving==='documents'} onSave={saveDocuments}/></div>}
 {section==='archive'&&<div className="space-y-5"><PanelTitle icon={FileText} title="Document Archive" desc="ค้นหาเอกสารจากเลขที่ ลูกค้า Order ID และประเภทเอกสาร"/><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาเลขเอกสาร / ลูกค้า / Order ID..." className="w-full rounded-2xl border border-slate-200 bg-slate-50 py-3 pl-10 pr-10 text-xs font-bold outline-none focus:ring-2 focus:ring-brand/20"/>{query&&<button onClick={()=>setQuery('')} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400"><X size={15}/></button>}</div>{archive.length===0?<div className="rounded-[24px] border border-dashed border-slate-300 p-10 text-center"><FileText className="mx-auto text-slate-300" size={30}/><div className="mt-3 text-sm font-black">ยังไม่มีเอกสารในคลัง</div><p className="mt-1 text-xs text-slate-400">เมื่อ Order / Payment / Delivery / Installation สร้างเอกสาร ระบบสามารถนำรายการมาแสดงที่นี่ได้โดยใช้ Document ID เดียวกัน</p></div>:<div className="overflow-x-auto rounded-[24px] border border-slate-200"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] font-black text-slate-400"><tr><th className="px-4 py-3">เลขเอกสาร</th><th className="px-4 py-3">ประเภท</th><th className="px-4 py-3">ลูกค้า</th><th className="px-4 py-3">Order</th><th className="px-4 py-3">สถานะ</th><th className="px-4 py-3">วันที่</th></tr></thead><tbody>{archive.map(x=><tr key={x.id} className="border-t border-slate-100"><td className="px-4 py-3 font-black">{x.number}</td><td className="px-4 py-3">{x.type}</td><td className="px-4 py-3 font-bold">{x.customer}</td><td className="px-4 py-3">{x.orderId||'-'}</td><td className="px-4 py-3">{x.status}</td><td className="px-4 py-3">{x.createdAt}</td></tr>)}</tbody></table></div>}</div>}
 </main></div></section>;
}
function PanelTitle({icon:Icon,title,desc}:{icon:any;title:string;desc:string}){return <div className="flex items-start gap-3"><span className="rounded-2xl bg-brand-soft p-3 text-brand"><Icon size={19}/></span><div><h3 className="text-base font-black">{title}</h3><p className="mt-1 text-[11px] font-medium text-slate-400">{desc}</p></div></div>}
function SaveBar({saving,onSave}:{saving:boolean;onSave:()=>void}){return <div className="sticky bottom-3 z-10 flex items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-lg backdrop-blur"><div className="flex items-center gap-2 text-[10px] font-bold text-slate-500"><Check size={15} className="text-emerald-500"/> บันทึกในเครื่องทันที และซิงก์ฐานข้อมูลเบื้องหลัง</div><button onClick={onSave} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-[10px] font-black text-white disabled:opacity-50"><Save size={14}/>{saving?'กำลังซิงก์…':'บันทึกการเปลี่ยนแปลง'}</button></div>}
