import React, { useEffect, useMemo, useState } from 'react';
import { doc, onSnapshot, setDoc } from 'firebase/firestore';
import { Building2, FileText, Landmark, MapPin, Save, ShieldCheck, Stamp, Trash2, UserRound, Wallet, RefreshCcw } from 'lucide-react';
import { db, handleFirestoreError, OperationType } from '../lib/firebase';
import { useAuth } from '../hooks/useAuth';
import { notifyReaction } from '../utils/feedback';
import { THAI_GEO_CACHE_KEY, THAI_GEO_URL } from '../data/thailandLocations';

interface BusinessProfile {
  shopName:string; companyNameTh:string; companyNameEn:string; taxId:string; branchName:string;
  phone:string; email:string; website:string; address:string; district:string; province:string; subdistrict:string; postalCode:string;
  logoUrl:string; receiptTitle:string; receiptFooter:string; invoicePrefix:string; receiptPrefix:string;
  nextInvoiceNumber:number; nextReceiptNumber:number; bankName:string; bankAccountName:string; bankAccountNumber:string;
  authorizedName:string; authorizedTitle:string; signatureUrl:string; stampUrl:string; updatedAt?:string; updatedBy?:string;
}

const DEFAULTS:BusinessProfile={
  shopName:'Solar order manager', companyNameTh:'โซล่าออเดอร์ เมเนเจอร์', companyNameEn:'Solar order manager', taxId:'', branchName:'สำนักงานใหญ่',
  phone:'', email:'', website:'', address:'', district:'', province:'', subdistrict:'', postalCode:'', logoUrl:'',
  receiptTitle:'ใบเสร็จรับเงิน / ใบรับเงิน', receiptFooter:'ขอบคุณที่ใช้บริการ', invoicePrefix:'INV-', receiptPrefix:'RC-',
  nextInvoiceNumber:1,nextReceiptNumber:1,bankName:'',bankAccountName:'',bankAccountNumber:'',authorizedName:'',authorizedTitle:'ผู้มีอำนาจลงนาม',signatureUrl:'',stampUrl:''
};

const sections=[['business','ข้อมูลธุรกิจ',Building2],['contact','ติดต่อและที่อยู่',MapPin],['documents','เอกสารและเลขที่',FileText],['payment','บัญชีรับเงิน',Landmark],['branding','โลโก้และลายเซ็น',Stamp]] as const;
type Section=typeof sections[number][0];
type Geo={name_th:string; districts:{name_th:string; sub_districts:{name_th:string; zip_code:number|string}[]}[]};

export default function BusinessDocumentsHub(){
 const {user,appUser}=useAuth(); const isAdmin=user?.email?.toLowerCase()==='b.b.thodsawat@gmail.com'||appUser?.role==='admin'||appUser?.role==='owner';
 const [data,setData]=useState(DEFAULTS); const [active,setActive]=useState<Section>('business'); const [saving,setSaving]=useState(false); const [loaded,setLoaded]=useState(false);
 const [geo,setGeo]=useState<Geo[]>([]); const [geoLoading,setGeoLoading]=useState(false); const [geoError,setGeoError]=useState(false);

 useEffect(()=>{if(!user)return; const ref=doc(db,'settings','businessProfile'); return onSnapshot(ref,s=>{setData({...DEFAULTS,...(s.exists()?s.data():{})} as BusinessProfile);setLoaded(true)},e=>{handleFirestoreError(e,OperationType.GET,'settings/businessProfile');setLoaded(true)})},[user]);
 useEffect(()=>{let cancelled=false; const load=async()=>{setGeoLoading(true);setGeoError(false);try{const cached=localStorage.getItem(THAI_GEO_CACHE_KEY);if(cached){const parsed=JSON.parse(cached);if(Array.isArray(parsed))setGeo(parsed)} const res=await fetch(THAI_GEO_URL,{cache:'force-cache'});if(!res.ok)throw new Error('geo fetch failed');const json=await res.json();if(!cancelled&&Array.isArray(json)){localStorage.setItem(THAI_GEO_CACHE_KEY,JSON.stringify(json));setGeo(json)}}catch{if(!cancelled&&!geo.length)setGeoError(true)}finally{if(!cancelled)setGeoLoading(false)}};load();return()=>{cancelled=true}},[]);
 const provinces=useMemo(()=>geo.map(p=>p.name_th).filter(Boolean),[geo]);
 const selectedProvince=useMemo(()=>geo.find(p=>p.name_th===data.province),[geo,data.province]);
 const districts=selectedProvince?.districts?.map(d=>d.name_th).filter(Boolean)??[];
 const selectedDistrict=selectedProvince?.districts?.find(d=>d.name_th===data.district);
 const subdistricts=selectedDistrict?.sub_districts?.map(s=>s.name_th).filter(Boolean)??[];
 const selectedSubdistrict=selectedDistrict?.sub_districts?.find(s=>s.name_th===data.subdistrict);
 const completion=useMemo(()=>{const keys:(keyof BusinessProfile)[]=['shopName','companyNameTh','companyNameEn','phone','address','province','district','subdistrict','postalCode'];return Math.round(keys.filter(k=>String(data[k]??'').trim()).length/keys.length*100)},[data]);
 const update=<K extends keyof BusinessProfile>(key:K,value:BusinessProfile[K])=>setData(p=>({...p,[key]:value}));
 const chooseProvince=(v:string)=>setData(p=>({...p,province:v,district:'',subdistrict:'',postalCode:''}));
 const chooseDistrict=(v:string)=>setData(p=>({...p,district:v,subdistrict:'',postalCode:''}));
 const chooseSubdistrict=(v:string)=>{const item=selectedDistrict?.sub_districts?.find(s=>s.name_th===v);setData(p=>({...p,subdistrict:v,postalCode:item?.zip_code?String(item.zip_code):''}))};
 const save=async()=>{if(!isAdmin)return notifyReaction('error','เฉพาะผู้ดูแลระบบหรือเจ้าของกิจการเท่านั้น');const required:[keyof BusinessProfile,string][]=[['shopName','ชื่อร้านค้า'],['companyNameTh','ชื่อบริษัทภาษาไทย'],['companyNameEn','ชื่อบริษัทภาษาอังกฤษ']];const missing=required.find(([k])=>!String(data[k]??'').trim());if(missing)return notifyReaction('warning',`กรุณากรอก${missing[1]}`);if(data.email&&!/^\S+@\S+\.\S+$/.test(data.email))return notifyReaction('warning','รูปแบบอีเมลไม่ถูกต้อง');if(data.postalCode&&!/^\d{5}$/.test(data.postalCode))return notifyReaction('warning','รหัสไปรษณีย์ต้องเป็นตัวเลข 5 หลัก');setSaving(true);try{await setDoc(doc(db,'settings','businessProfile'),{...data,updatedAt:new Date().toISOString(),updatedBy:user?.uid||''});notifyReaction('success','บันทึกข้อมูลธุรกิจและเอกสารเรียบร้อย')}catch(e){handleFirestoreError(e,OperationType.WRITE,'settings/businessProfile');notifyReaction('error','บันทึกไม่สำเร็จ กรุณาตรวจสอบสิทธิ์ Firestore')}finally{setSaving(false)}};
 const clearForm=()=>{if(!isAdmin)return notifyReaction('error','เฉพาะผู้ดูแลระบบหรือเจ้าของกิจการเท่านั้น');setData(DEFAULTS);notifyReaction('success','ล้างข้อมูลในฟอร์มแล้ว — ยังไม่ได้ลบข้อมูลบนฐานข้อมูล')};
 const Field=({label,value,onChange,type='text',placeholder}:{label:string;value:string|number;onChange:(v:string)=>void;type?:string;placeholder?:string})=><label className="block space-y-1.5"><span className="text-[11px] font-black text-slate-500">{label}</span><input disabled={!isAdmin||saving} type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-900 outline-none focus:ring-2 focus:ring-brand/20 disabled:opacity-60 placeholder:text-slate-400"/></label>;
 const SelectField=({label,value,onChange,options,disabled,placeholder}:{label:string;value:string;onChange:(v:string)=>void;options:string[];disabled?:boolean;placeholder:string})=><label className="block space-y-1.5"><span className="text-[11px] font-black text-slate-500">{label}</span><select disabled={!isAdmin||saving||disabled} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-900 outline-none focus:ring-2 focus:ring-brand/20 disabled:opacity-60"><option value="">{placeholder}</option>{options.map(o=><option key={o} value={o}>{o}</option>)}</select></label>;
 if(!loaded)return <div className="rounded-[28px] bg-white border border-slate-200 p-8 text-sm font-bold text-slate-500">กำลังโหลดข้อมูลธุรกิจ...</div>;
 const header=(title:string,Icon:any)=><div className="flex items-center gap-3"><span className="rounded-2xl bg-brand-soft text-brand p-3"><Icon size={19}/></span><div><h3 className="text-base font-black">{title}</h3><p className="text-[11px] text-slate-400 font-semibold">ข้อมูลส่วนกลาง ใช้ร่วมกันทุกเอกสาร</p></div></div>;
 return <section className="rounded-[28px] border border-slate-200 bg-white shadow-sm overflow-hidden"><div className="p-5 sm:p-7 border-b border-slate-100"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="inline-flex items-center gap-2 rounded-full bg-brand-soft px-3 py-1 text-[10px] font-black text-brand"><ShieldCheck size={13}/> SINGLE SOURCE OF TRUTH</div><h2 className="mt-3 text-xl sm:text-2xl font-black">ข้อมูลธุรกิจและเอกสาร</h2><p className="mt-1 text-xs font-medium text-slate-500">กรอกครั้งเดียว ใช้ร่วมกันทุกเอกสาร และตรวจสอบข้อมูลก่อนบันทึก</p></div><div className="flex flex-wrap items-center gap-2"><div className="min-w-[130px]"><div className="flex justify-between text-[10px] font-black text-slate-400 mb-1"><span>ความครบถ้วน</span><span>{completion}%</span></div><div className="h-2 rounded-full bg-slate-100 overflow-hidden"><div className="h-full rounded-full bg-brand" style={{width:`${completion}%`}}/></div></div><button onClick={clearForm} disabled={!isAdmin||saving} className="rounded-2xl border border-slate-200 bg-white text-slate-700 px-3 py-3 text-xs font-black flex items-center gap-2 disabled:opacity-50"><Trash2 size={15}/>ล้างฟอร์ม</button><button onClick={save} disabled={!isAdmin||saving} className="rounded-2xl bg-slate-900 text-white px-4 py-3 text-xs font-black flex items-center gap-2 disabled:opacity-50"><Save size={15}/>{saving?'กำลังบันทึก':'บันทึกทั้งหมด'}</button></div></div></div>
 <div className="grid lg:grid-cols-[230px_1fr] min-h-[560px]"><nav className="border-b lg:border-b-0 lg:border-r border-slate-100 p-3 bg-slate-50/70 flex lg:flex-col gap-1 overflow-x-auto">{sections.map(([id,label,Icon])=><button key={id} onClick={()=>setActive(id)} className={`shrink-0 flex items-center gap-3 rounded-2xl px-3 py-3 text-left ${active===id?'bg-slate-900 text-white shadow-sm':'text-slate-600 hover:bg-white'}`}><Icon size={17}/><span className="text-xs font-black whitespace-nowrap">{label}</span></button>)}</nav><div className="p-5 sm:p-7">
 {active==='business'&&<div className="space-y-5">{header('ข้อมูลธุรกิจ',Building2)}<div className="grid sm:grid-cols-2 gap-4"><Field label="ชื่อร้านค้า" value={data.shopName} placeholder="เช่น Solar order manager" onChange={v=>update('shopName',v)}/><Field label="ชื่อบริษัทภาษาไทย" value={data.companyNameTh} placeholder="เช่น โซล่าออเดอร์ เมเนเจอร์" onChange={v=>update('companyNameTh',v)}/><Field label="ชื่อบริษัทภาษาอังกฤษ" value={data.companyNameEn} placeholder="เช่น Solar order manager" onChange={v=>update('companyNameEn',v)}/><Field label="เลขประจำตัวผู้เสียภาษี" value={data.taxId} placeholder="เช่น 010555XXXXXXXX" onChange={v=>update('taxId',v)}/><Field label="สาขา" value={data.branchName} placeholder="เช่น สำนักงานใหญ่" onChange={v=>update('branchName',v)}/><Field label="เว็บไซต์" value={data.website} placeholder="เช่น https://example.com" onChange={v=>update('website',v)}/></div></div>}
 {active==='contact'&&<div className="space-y-5">{header('ติดต่อและที่อยู่',MapPin)}<div className="grid sm:grid-cols-2 gap-4"><Field label="เบอร์โทรศัพท์" value={data.phone} placeholder="เช่น 08X-XXX-XXXX" onChange={v=>update('phone',v)} type="tel"/><Field label="อีเมล" value={data.email} placeholder="เช่น info@example.com" onChange={v=>update('email',v)} type="email"/><div className="sm:col-span-2"><Field label="ที่อยู่ / บ้านเลขที่ / หมู่" value={data.address} placeholder="เช่น 99/9 หมู่ 5" onChange={v=>update('address',v)}/></div><SelectField label="จังหวัด" value={data.province} onChange={chooseProvince} options={provinces} disabled={geoLoading} placeholder={geoLoading?'กำลังโหลดจังหวัด...':geoError?'โหลดข้อมูลที่อยู่ไม่สำเร็จ':'เลือกจังหวัด'}/><SelectField label="อำเภอ / เขต" value={data.district} onChange={chooseDistrict} options={districts} disabled={!data.province} placeholder="เลือกอำเภอ / เขต"/><SelectField label="ตำบล / แขวง" value={data.subdistrict} onChange={chooseSubdistrict} options={subdistricts} disabled={!data.district} placeholder="เลือกตำบล / แขวง"/><Field label="รหัสไปรษณีย์ (อัตโนมัติ)" value={data.postalCode} placeholder="ระบบเติมให้อัตโนมัติ" onChange={()=>undefined}/></div>{geoError&&<div className="rounded-2xl bg-rose-50 border border-rose-200 p-4 text-xs font-bold text-rose-700 flex items-center justify-between gap-3"><span>ไม่สามารถโหลดฐานข้อมูลจังหวัด/อำเภอ/ตำบลได้ กรุณาตรวจสอบอินเทอร์เน็ต</span><button onClick={()=>window.location.reload()} className="shrink-0 rounded-xl bg-rose-600 text-white px-3 py-2 flex items-center gap-1"><RefreshCcw size={13}/>ลองใหม่</button></div>}<p className="text-[11px] text-slate-400 font-semibold">เลือก จังหวัด → อำเภอ/เขต → ตำบล/แขวง แล้วระบบเติมรหัสไปรษณีย์ให้อัตโนมัติ ไม่ต้องพิมพ์เอง</p></div>}
 {active==='documents'&&<div className="space-y-5">{header('เอกสารและเลขที่อัตโนมัติ',FileText)}<div className="grid sm:grid-cols-2 gap-4"><Field label="หัวใบเสร็จ" value={data.receiptTitle} placeholder="เช่น ใบเสร็จรับเงิน / ใบรับเงิน" onChange={v=>update('receiptTitle',v)}/><Field label="ข้อความท้ายเอกสาร" value={data.receiptFooter} placeholder="เช่น ขอบคุณที่ใช้บริการ" onChange={v=>update('receiptFooter',v)}/><Field label="Prefix ใบแจ้งหนี้" value={data.invoicePrefix} placeholder="เช่น INV-" onChange={v=>update('invoicePrefix',v)}/><Field label="เลขถัดไป (ใบแจ้งหนี้)" value={data.nextInvoiceNumber} placeholder="เช่น 1" onChange={v=>update('nextInvoiceNumber',Math.max(1,Number(v)||1))} type="number"/><Field label="Prefix ใบเสร็จ" value={data.receiptPrefix} placeholder="เช่น RC-" onChange={v=>update('receiptPrefix',v)}/><Field label="เลขถัดไป (ใบเสร็จ)" value={data.nextReceiptNumber} placeholder="เช่น 1" onChange={v=>update('nextReceiptNumber',Math.max(1,Number(v)||1))} type="number"/></div></div>}
 {active==='payment'&&<div className="space-y-5">{header('บัญชีรับเงิน',Landmark)}<div className="grid sm:grid-cols-2 gap-4"><Field label="ธนาคาร" value={data.bankName} placeholder="เช่น กสิกรไทย" onChange={v=>update('bankName',v)}/><Field label="ชื่อบัญชี" value={data.bankAccountName} placeholder="เช่น บริษัท โซล่าออเดอร์ เมเนเจอร์" onChange={v=>update('bankAccountName',v)}/><Field label="เลขที่บัญชี" value={data.bankAccountNumber} placeholder="เช่น 123-4-56789-0" onChange={v=>update('bankAccountNumber',v)}/></div><div className="rounded-2xl bg-slate-50 border border-slate-200 p-4 text-xs text-slate-500 flex gap-2"><Wallet size={16}/>ข้อมูลบัญชีนี้ใช้เป็นข้อมูลอ้างอิงบนเอกสารและหน้าชำระเงิน</div></div>}
 {active==='branding'&&<div className="space-y-5">{header('โลโก้ ลายเซ็น และตราประทับ',Stamp)}<div className="grid sm:grid-cols-2 gap-4"><Field label="URL โลโก้" value={data.logoUrl} placeholder="เช่น https://.../logo.png" onChange={v=>update('logoUrl',v)}/><Field label="URL ลายเซ็น" value={data.signatureUrl} placeholder="เช่น https://.../signature.png" onChange={v=>update('signatureUrl',v)}/><Field label="URL ตราประทับ" value={data.stampUrl} placeholder="เช่น https://.../stamp.png" onChange={v=>update('stampUrl',v)}/><Field label="ชื่อผู้มีอำนาจลงนาม" value={data.authorizedName} placeholder="เช่น นาย..." onChange={v=>update('authorizedName',v)}/><Field label="ตำแหน่ง" value={data.authorizedTitle} placeholder="เช่น กรรมการผู้จัดการ" onChange={v=>update('authorizedTitle',v)}/></div></div>}
 </div></div>{!isAdmin&&<div className="border-t border-amber-100 bg-amber-50 px-5 py-3 text-xs font-bold text-amber-800 flex items-center gap-2"><UserRound size={15}/> โหมดดูอย่างเดียว: เฉพาะเจ้าของ/ผู้ดูแลระบบที่แก้ไขข้อมูลธุรกิจได้</div>}</section>;
}
