import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock, Database, HardDrive, RefreshCw, Search, ShieldAlert, Trash2, Wifi } from 'lucide-react';
import { format } from 'date-fns';
import { th } from 'date-fns/locale';
import { dbManager, DbSyncError } from '../lib/dbManager';
import { notifyReaction } from '../utils/feedback';

export default function ErrorLogger() {
  const [logs, setLogs] = useState<DbSyncError[]>([]);
  const [search, setSearch] = useState('');
  const [sourceFilter, setSourceFilter] = useState<'all' | 'local' | 'firebase' | 'network'>('all');
  const loadLogs = () => setLogs(dbManager.getErrorLogs());
  useEffect(() => { loadLogs(); const unsubscribe = dbManager.subscribe(loadLogs); return () => { unsubscribe(); }; }, []);
  const clear = () => { if (confirm('คุณต้องการลบประวัติข้อผิดพลาดทั้งหมดใช่หรือไม่?')) { dbManager.clearErrorLogs(); notifyReaction('success', 'ล้างประวัติข้อผิดพลาดสำเร็จ'); loadLogs(); } };
  const simulate = (source: 'firebase' | 'local') => { const message = source === 'firebase' ? 'Firebase Firestore simulated connection failure.' : 'LocalStorage simulated quota failure.'; dbManager.addErrorLog(source, 'Simulated failure', message, false); loadLogs(); notifyReaction('success', `จำลองข้อผิดพลาด ${source} สำเร็จ`); };
  const filtered = logs.filter(log => (sourceFilter === 'all' || log.source === sourceFilter) && `${log.errorMessage} ${log.errorType}`.toLowerCase().includes(search.toLowerCase()));
  const badge = (source: DbSyncError['source']) => source === 'firebase' ? <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-black bg-indigo-50 text-indigo-600 border border-indigo-200"><Database size={11}/> FIREBASE</span> : source === 'local' ? <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-black bg-amber-50 text-amber-600 border border-amber-200"><HardDrive size={11}/> LOCAL</span> : <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-black bg-rose-50 text-rose-600 border border-rose-200"><Wifi size={11}/> NETWORK</span>;
  return <div className="bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 p-6 sm:p-8 space-y-6">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h3 className="text-base font-black flex items-center gap-2"><ShieldAlert size={20} className="text-rose-500"/> บันทึกข้อผิดพลาดของระบบ</h3><p className="text-xs text-slate-500 mt-1">ตรวจสอบ Firebase, LocalStorage และเครือข่าย</p></div>{logs.length > 0 && <button onClick={clear} className="px-4 py-2 bg-rose-50 text-rose-600 rounded-xl text-xs font-black flex items-center gap-2"><Trash2 size={13}/> ล้างบันทึก</button>}</div>
    <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-2xl border border-slate-200 dark:border-slate-800"><div className="flex items-center gap-2 text-[10px] font-black text-slate-400 mb-3"><RefreshCw size={12}/> เครื่องมือจำลอง</div><div className="flex flex-wrap gap-2"><button onClick={() => simulate('firebase')} className="px-3 py-2 bg-indigo-50 text-indigo-700 rounded-xl text-[11px] font-bold">จำลอง Firebase ขัดข้อง</button><button onClick={() => simulate('local')} className="px-3 py-2 bg-amber-50 text-amber-700 rounded-xl text-[11px] font-bold">จำลอง LocalStorage เต็ม</button></div></div>
    <div className="flex flex-col sm:flex-row gap-3"><div className="relative flex-1"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="ค้นหาข้อผิดพลาด..." className="w-full pl-9 pr-4 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs font-bold"/></div><div className="flex gap-1 bg-slate-50 dark:bg-slate-800 p-1 rounded-xl">{(['all','local','firebase','network'] as const).map(src => <button key={src} onClick={() => setSourceFilter(src)} className={`px-3 py-1.5 rounded-lg text-[10px] font-black uppercase ${sourceFilter === src ? 'bg-white dark:bg-slate-900 shadow' : 'text-slate-400'}`}>{src}</button>)}</div></div>
    {filtered.length ? <div className="space-y-3">{filtered.map(log => <div key={log.id} className="p-4 rounded-2xl bg-slate-50/60 dark:bg-slate-800/30 border border-slate-200 dark:border-slate-800 flex items-start gap-3"><span className="p-2 bg-rose-50 text-rose-500 rounded-xl"><AlertTriangle size={16}/></span><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2">{badge(log.source)}<span className="text-[10px] font-bold text-slate-400">{log.errorType}</span></div><p className="text-xs font-bold mt-2 break-all">{log.errorMessage}</p><span className="text-[10px] text-slate-400 flex items-center gap-1 mt-2"><Clock size={11}/>{format(new Date(log.timestamp), 'dd MMM yyyy, HH:mm:ss น.', { locale: th })}</span></div></div>)}</div> : <div className="p-12 text-center border border-dashed border-slate-200 dark:border-slate-800 rounded-3xl"><CheckCircle2 size={34} className="mx-auto text-emerald-500 mb-2"/><p className="text-xs font-black">ไม่พบข้อผิดพลาด</p></div>}
  </div>;
}
