import { useEffect, useState } from 'react';
import { Check, Eye, EyeOff, KeyRound, Monitor, Moon, Palette, ShieldCheck, Sun, WandSparkles } from 'lucide-react';
import { motion } from 'motion/react';
import { auth } from '../lib/firebase';
import { doc, getDoc, setDoc, serverTimestamp } from '../lib/firestore-compat';

type LoginSettings = { theme_mode:'light'|'dark'|'system'; animation:'ambient'|'minimal'|'none'; show_developer_credit:boolean; developer_credit_name:string; show_developer_credit_on_home:boolean; show_developer_credit_on_login:boolean; welcome_title:string; welcome_subtitle:string; allow_google_login:boolean; allow_password_login:boolean; };
const defaults:LoginSettings={theme_mode:'light',animation:'ambient',show_developer_credit:true,developer_credit_name:'BOY THODSAWAT',show_developer_credit_on_home:true,show_developer_credit_on_login:true,welcome_title:'Solar Order Manager',welcome_subtitle:'ระบบจัดการออเดอร์โซล่าเซลล์ครบทุกฟีเจอร์ เพื่อธุรกิจของคุณ',allow_google_login:true,allow_password_login:true};

export default function LoginControlCenter(){
 const [s,setS]=useState<LoginSettings>(defaults); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false);
 useEffect(()=>{void(async()=>{try{const snapshot=await getDoc(doc(null,'login_settings','default'));if(snapshot.exists())setS({...defaults,...snapshot.data() as Partial<LoginSettings>});}catch(error){console.warn('[Firebase login settings]',error);}})();},[]);
 const patch=(p:Partial<LoginSettings>)=>{setSaved(false);setS(v=>({...v,...p}));};
 const save=async()=>{if(!auth?.currentUser)return;setSaving(true);try{await setDoc(doc(null,'login_settings','default'),{...s,updated_by:auth.currentUser.uid,updated_at:serverTimestamp()},{merge:true});setSaved(true);}catch(error){console.error('[Firebase login settings save]',error);setSaved(false);}finally{setSaving(false);}};
 const themes:[LoginSettings['theme_mode'],string,any][]=[['light','สว่าง',Sun],['dark','มืด',Moon],['system','ตามระบบ',Monitor]];
 return <div className="space-y-6"><div className="rounded-3xl overflow-hidden border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-sm"><div className="relative p-6 sm:p-8 bg-gradient-to-br from-sky-500 via-blue-600 to-indigo-700 text-white overflow-hidden"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-white/15 blur-3xl"/><div className="absolute -left-16 -bottom-20 h-56 w-56 rounded-full bg-cyan-200/20 blur-3xl"/><div className="relative"><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/10 border border-white/15 text-[10px] font-black uppercase"><WandSparkles size={14}/> Login Control Center</div><h2 className="mt-4 text-2xl sm:text-3xl font-black">ศูนย์ควบคุมการเข้าสู่ระบบ</h2><p className="mt-2 text-sm text-white/75">กำหนดวิธีเข้าสู่ระบบและหน้าตา Login จาก Command Center จุดเดียว</p></div></div><div className="p-5 sm:p-8 space-y-8">
 <section><h3 className="text-sm font-black flex items-center gap-2 text-slate-900 dark:text-white"><KeyRound size={17} className="text-blue-500"/> วิธีเข้าสู่ระบบ</h3><div className="grid sm:grid-cols-2 gap-3 mt-3"><button onClick={()=>patch({allow_password_login:!s.allow_password_login})} className={`rounded-2xl border p-4 text-left transition ${s.allow_password_login?'border-blue-500 bg-blue-50 dark:bg-blue-950/30':'border-slate-200 dark:border-slate-800'}`}><div className="flex items-center justify-between"><div className="flex items-center gap-2"><KeyRound size={18} className="text-blue-500"/><span className="text-sm font-black">อีเมล + รหัสผ่าน</span></div>{s.allow_password_login&&<Check size={17} className="text-emerald-500"/>}</div><p className="mt-2 text-[11px] text-slate-400">Firebase Email/Password พร้อมลืมรหัสผ่าน</p></button><button onClick={()=>patch({allow_google_login:!s.allow_google_login})} className={`rounded-2xl border p-4 text-left transition ${s.allow_google_login?'border-blue-500 bg-blue-50 dark:bg-blue-950/30':'border-slate-200 dark:border-slate-800'}`}><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="font-black text-lg">G</span><span className="text-sm font-black">Google Authentication</span></div>{s.allow_google_login&&<Check size={17} className="text-emerald-500"/>}</div><p className="mt-2 text-[11px] text-slate-400">Google OAuth ผ่าน Firebase Authentication</p></button></div><div className="mt-3 flex items-start gap-2 rounded-2xl bg-amber-50 dark:bg-amber-950/20 p-3 text-[11px] text-amber-700 dark:text-amber-300"><ShieldCheck size={15} className="shrink-0"/>อย่างน้อยควรเปิดไว้ 1 วิธี เพื่อไม่ให้ผู้ใช้ถูกล็อกออกจากระบบ</div></section>
 <section><h3 className="text-sm font-black flex items-center gap-2 text-slate-900 dark:text-white"><Palette size={17} className="text-indigo-500"/> โหมดธีม Login</h3><div className="grid grid-cols-3 gap-2 mt-3">{themes.map(([id,label,Icon])=><button key={id} onClick={()=>patch({theme_mode:id})} className={`p-4 rounded-2xl border text-left ${s.theme_mode===id?'border-indigo-500 bg-indigo-50 dark:bg-indigo-950/40':'border-slate-200 dark:border-slate-800'}`}><Icon size={18}/><p className="mt-2 text-xs font-black">{label}</p>{s.theme_mode===id&&<Check size={14} className="mt-2 text-indigo-500"/>}</button>)}</div></section>
 <section><h3 className="text-sm font-black text-slate-900 dark:text-white">Animation</h3><div className="flex flex-wrap gap-2 mt-3">{([['ambient','Ambient Glow'],['minimal','Minimal Motion'],['none','ปิด Animation']] as const).map(([id,label])=><button key={id} onClick={()=>patch({animation:id})} className={`px-4 py-2.5 rounded-xl border text-xs font-black ${s.animation===id?'bg-indigo-600 text-white border-indigo-600':'border-slate-200 dark:border-slate-800'}`}>{label}</button>)}</div></section>
 <section className="grid md:grid-cols-2 gap-4"><label className="text-xs font-black">ชื่อระบบ<input value={s.welcome_title} onChange={e=>patch({welcome_title:e.target.value})} className="mt-2 w-full px-4 py-3 rounded-xl border bg-slate-50 dark:bg-slate-950 dark:border-slate-800"/></label><label className="text-xs font-black">คำอธิบาย<input value={s.welcome_subtitle} onChange={e=>patch({welcome_subtitle:e.target.value})} className="mt-2 w-full px-4 py-3 rounded-xl border bg-slate-50 dark:bg-slate-950 dark:border-slate-800"/></label></section>
 <section className="rounded-2xl border border-slate-200 dark:border-slate-800 p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-black">เครดิตผู้พัฒนา</p><p className="text-[11px] text-slate-400 mt-1">กำหนดชื่อและตำแหน่งการแสดงผล</p></div><button onClick={()=>patch({show_developer_credit:!s.show_developer_credit})} className={`w-12 h-7 rounded-full p-1 ${s.show_developer_credit?'bg-indigo-600':'bg-slate-300 dark:bg-slate-700'}`}><span className={`block w-5 h-5 bg-white rounded-full transition-transform ${s.show_developer_credit?'translate-x-5':''}`}/></button></div><input value={s.developer_credit_name} onChange={e=>patch({developer_credit_name:e.target.value})} className="mt-4 w-full px-4 py-3 rounded-xl border bg-slate-50 dark:bg-slate-950 dark:border-slate-800 font-black"/><div className="grid grid-cols-2 gap-2 mt-3"><button onClick={()=>patch({show_developer_credit_on_login:!s.show_developer_credit_on_login})} className="p-3 rounded-xl border text-xs font-bold flex justify-between">หน้า Login {s.show_developer_credit_on_login?<Eye size={15} className="text-emerald-500"/>:<EyeOff size={15}/>}</button><button onClick={()=>patch({show_developer_credit_on_home:!s.show_developer_credit_on_home})} className="p-3 rounded-xl border text-xs font-bold flex justify-between">หน้าแรก {s.show_developer_credit_on_home?<Eye size={15} className="text-emerald-500"/>:<EyeOff size={15}/>}</button></div></section>
 <div className="flex justify-end"><button onClick={save} disabled={saving||(!s.allow_google_login&&!s.allow_password_login)} className="px-6 py-3 rounded-xl bg-blue-600 text-white text-xs font-black disabled:opacity-60">{saving?'กำลังบันทึก...':saved?'บันทึกแล้ว ✓':'บันทึกการตั้งค่า Login'}</button></div>
 </div></div><div className="rounded-3xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 p-5 flex items-center gap-3"><motion.div animate={s.animation==='ambient'?{scale:[1,1.08,1],opacity:[.7,1,.7]}:{}} transition={{duration:3,repeat:Infinity}} className="w-12 h-12 rounded-2xl bg-gradient-to-br from-sky-500 to-blue-600 flex items-center justify-center text-white"><ShieldCheck size={20}/></motion.div><div><p className="text-sm font-black">Login Security</p><p className="text-[11px] text-slate-400">{s.allow_password_login?'Email/Password ':''}{s.allow_google_login?'Google':''} • Firebase Authentication</p></div></div></div>;
}
