import { useEffect, useState } from 'react';
import { Check, Eye, EyeOff, Monitor, Moon, Palette, Sun, Sparkles, WandSparkles } from 'lucide-react';
import { motion } from 'motion/react';
import { getSupabase } from '../lib/supabase';

type LoginSettings = { theme_mode:'light'|'dark'|'system'; layout_style:'split-left'|'split-right'|'centered'; animation:'ambient'|'minimal'|'none'; show_developer_credit:boolean; developer_credit_name:string; show_developer_credit_on_home:boolean; show_developer_credit_on_login:boolean; welcome_title:string; welcome_subtitle:string; };
const defaults:LoginSettings={theme_mode:'dark',layout_style:'split-left',animation:'ambient',show_developer_credit:true,developer_credit_name:'BOY THODSAWAT',show_developer_credit_on_home:true,show_developer_credit_on_login:true,welcome_title:'ศูนย์ควบคุมระบบ',welcome_subtitle:'จัดการงานขาย ระบบโซล่า และการเงินของคุณได้ในที่เดียว'};
export default function LoginControlCenter(){
 const [s,setS]=useState<LoginSettings>(defaults); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false);
 useEffect(()=>{void(async()=>{const c=getSupabase();if(!c)return;const {data}=await c.from('login_settings').select('*').eq('id','default').maybeSingle();if(data)setS({...defaults,...data});})();},[]);
 const patch=(p:Partial<LoginSettings>)=>{setSaved(false);setS(v=>({...v,...p}));};
 const save=async()=>{const c=getSupabase();if(!c)return;setSaving(true);const {data:{user}}=await c.auth.getUser();if(!user){setSaving(false);return;}const {error}=await c.from('login_settings').upsert({...s,id:'default',updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:'id'});setSaved(!error);setSaving(false);};
 const themes:[LoginSettings['theme_mode'],string,any][]=[['light','สว่าง',Sun],['dark','มืด',Moon],['system','ตามระบบ',Monitor]];
 return <div className="space-y-6"><div className="rounded-3xl overflow-hidden border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-sm"><div className="p-6 sm:p-8 bg-gradient-to-br from-indigo-600 via-violet-600 to-slate-950 text-white"><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/10 border border-white/15 text-[10px] font-black uppercase"><WandSparkles size={14}/> Login Control Center</div><h2 className="mt-4 text-2xl sm:text-3xl font-black">ออกแบบหน้าเข้าสู่ระบบ</h2><p className="mt-2 text-sm text-white/70">จัดการธีม เลย์เอาต์ Animation และเครดิตผู้พัฒนา</p></div><div className="p-5 sm:p-8 space-y-8">
 <section><h3 className="text-sm font-black flex items-center gap-2 text-slate-900 dark:text-white"><Palette size={17} className="text-indigo-500"/> โหมดธีม</h3><div className="grid grid-cols-3 gap-2 mt-3">{themes.map(([id,label,Icon])=><button key={id} onClick={()=>patch({theme_mode:id})} className={`p-4 rounded-2xl border text-left ${s.theme_mode===id?'border-indigo-500 bg-indigo-50 dark:bg-indigo-950/40':'border-slate-200 dark:border-slate-800'}`}><Icon size={18}/><p className="mt-2 text-xs font-black">{label}</p>{s.theme_mode===id&&<Check size={14} className="mt-2 text-indigo-500"/>}</button>)}</div></section>
 <section><h3 className="text-sm font-black text-slate-900 dark:text-white">รูปแบบหน้า Login</h3><div className="grid sm:grid-cols-3 gap-3 mt-3">{[['split-left','Branding ซ้าย / ฟอร์มขวา'],['split-right','ฟอร์มซ้าย / Branding ขวา'],['centered','การ์ดกลางมินิมอล']].map(([id,label])=><button key={id} onClick={()=>patch({layout_style:id as LoginSettings['layout_style']})} className={`p-4 rounded-2xl border text-left ${s.layout_style===id?'border-indigo-500 bg-indigo-50 dark:bg-indigo-950/40':'border-slate-200 dark:border-slate-800'}`}><div className="h-12 rounded-xl bg-slate-100 dark:bg-slate-800 p-2 flex gap-1"><span className={`rounded-lg bg-indigo-500/80 ${id==='centered'?'w-full':'w-1/2'}`}/>{id!=='centered'&&<span className="flex-1 rounded-lg bg-white dark:bg-slate-700"/>}</div><p className="mt-3 text-xs font-black">{label}</p></button>)}</div></section>
 <section><h3 className="text-sm font-black text-slate-900 dark:text-white">Animation</h3><div className="flex flex-wrap gap-2 mt-3">{([['ambient','Ambient Glow'],['minimal','Minimal Motion'],['none','ปิด Animation']] as const).map(([id,label])=><button key={id} onClick={()=>patch({animation:id})} className={`px-4 py-2.5 rounded-xl border text-xs font-black ${s.animation===id?'bg-indigo-600 text-white border-indigo-600':'border-slate-200 dark:border-slate-800'}`}>{label}</button>)}</div></section>
 <section className="grid md:grid-cols-2 gap-4"><label className="text-xs font-black">หัวข้อ<input value={s.welcome_title} onChange={e=>patch({welcome_title:e.target.value})} className="mt-2 w-full px-4 py-3 rounded-xl border bg-slate-50 dark:bg-slate-950 dark:border-slate-800"/></label><label className="text-xs font-black">คำโปรย<input value={s.welcome_subtitle} onChange={e=>patch({welcome_subtitle:e.target.value})} className="mt-2 w-full px-4 py-3 rounded-xl border bg-slate-50 dark:bg-slate-950 dark:border-slate-800"/></label></section>
 <section className="rounded-2xl border border-slate-200 dark:border-slate-800 p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-black">เครดิตผู้พัฒนา</p><p className="text-[11px] text-slate-400 mt-1">แสดงเด่น พร้อม Animation ได้</p></div><button onClick={()=>patch({show_developer_credit:!s.show_developer_credit})} className={`w-12 h-7 rounded-full p-1 ${s.show_developer_credit?'bg-indigo-600':'bg-slate-300 dark:bg-slate-700'}`}><span className={`block w-5 h-5 bg-white rounded-full transition-transform ${s.show_developer_credit?'translate-x-5':''}`}/></button></div><input value={s.developer_credit_name} onChange={e=>patch({developer_credit_name:e.target.value})} className="mt-4 w-full px-4 py-3 rounded-xl border bg-slate-50 dark:bg-slate-950 dark:border-slate-800 font-black"/><div className="grid grid-cols-2 gap-2 mt-3"><button onClick={()=>patch({show_developer_credit_on_login:!s.show_developer_credit_on_login})} className="p-3 rounded-xl border text-xs font-bold flex justify-between">หน้า Login {s.show_developer_credit_on_login?<Eye size={15} className="text-emerald-500"/>:<EyeOff size={15}/>}</button><button onClick={()=>patch({show_developer_credit_on_home:!s.show_developer_credit_on_home})} className="p-3 rounded-xl border text-xs font-bold flex justify-between">หน้าแรก {s.show_developer_credit_on_home?<Eye size={15} className="text-emerald-500"/>:<EyeOff size={15}/>}</button></div></section>
 <div className="flex justify-end"><button onClick={save} disabled={saving} className="px-6 py-3 rounded-xl bg-indigo-600 text-white text-xs font-black disabled:opacity-60">{saving?'กำลังบันทึก...':saved?'บันทึกแล้ว ✓':'บันทึกการตั้งค่า'}</button></div>
 </div></div><div className="rounded-3xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 p-5 flex items-center gap-3"><motion.div animate={s.animation==='ambient'?{scale:[1,1.08,1],opacity:[.7,1,.7]}:{}} transition={{duration:3,repeat:Infinity}} className="w-12 h-12 rounded-2xl bg-gradient-to-br from-indigo-500 to-cyan-400 flex items-center justify-center text-white"><Sparkles size={20}/></motion.div><div><p className="text-sm font-black">{s.developer_credit_name}</p><p className="text-[11px] text-slate-400">{s.theme_mode} • {s.layout_style} • {s.animation}</p></div></div></div>;
}
