import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const initial = [{ id: 'offline_1', amount: 10 }, { id: 'offline_2', amount: 20 }];
const snapshotById = new Map(initial.map(item => [item.id, JSON.stringify(item)]));
const latest = [{ id: 'offline_1', amount: 99 }, initial[1], { id: 'offline_3', amount: 30 }];
const remaining = latest.filter(item => snapshotById.get(item.id) !== JSON.stringify(item));
assert.deepEqual(remaining, [{ id: 'offline_1', amount: 99 }, { id: 'offline_3', amount: 30 }], 'edits and appended entries must survive an in-flight flush');

const firebase = readFileSync('src/lib/firebase.ts', 'utf8');
const dbManager = readFileSync('src/lib/dbManager.ts', 'utf8');
const transactionsHook = readFileSync('src/hooks/useTransactions.ts', 'utf8');
const cloudStatusHook = readFileSync('src/hooks/useCloudSyncStatus.ts', 'utf8');
const resetService = readFileSync('src/lib/systemResetService.ts', 'utf8');
const resetComponent = readFileSync('src/components/SystemResetSettings.tsx', 'utf8');
const customersHook = readFileSync('src/hooks/useCustomers.ts', 'utf8');
assert.match(firebase, /persistentLocalCache\(/, 'Firestore must use a persistent local cache for reload-safe offline sync');
assert.match(firebase, /persistentSingleTabManager\(/, 'persistent cache must define a tab manager');
assert.match(firebase, /function createFirestore\(/, 'Firestore initialization must safely handle existing app instances');
assert.match(dbManager, /function mutateQueue\(/, 'all queue mutations must use a latest-state coordinator');
assert.match(dbManager, /snapshotById/, 'flush reconciliation must compare exact committed snapshots');
assert.match(dbManager, /start \+= 450/, 'large queues must be committed in batches below Firestore limits');
assert.match(transactionsHook, /dbManager\.enqueueOfflineTransaction/, 'offline create must use the shared queue coordinator');
assert.match(transactionsHook, /dbManager\.updateOfflineQueueTransaction/, 'offline update must use the shared queue coordinator');
assert.match(transactionsHook, /dbManager\.removeOfflineQueueTransaction/, 'offline delete must use the shared queue coordinator');
assert.match(transactionsHook, /function mergeTransactions/, 'UI must deduplicate queued and cloud copies by transaction ID');
assert.match(transactionsHook, /start \+= 450/, 'bulk deletion must respect Firestore batch limits');
assert.match(transactionsHook, /await dbManager\.flushOfflineQueue\(\)/, 'transaction hook must use the shared queue flusher');
assert.match(cloudStatusHook, /await dbManager\.flushOfflineQueue\(\)/, 'manual and interval sync must use the shared queue flusher');
assert.doesNotMatch(cloudStatusHook, /addDoc\(/, 'manual sync must not create a second ID-generating upload path');
assert.match(customersHook, /start \+= 450/, 'customer factory reset deletion must respect Firestore batch limits');
assert.match(customersHook, /Customer reset verification failed/, 'customer deletion must verify no documents remain');
assert.match(resetService, /FACTORY_RESET_COLLECTIONS/, 'factory reset must use an explicit business-data scope');
assert.match(resetService, /BATCH_LIMIT = 450/, 'factory reset must stay below Firestore batch limits');
assert.match(resetService, /assertFactoryResetAuthorized/, 'destructive reset service must authorize at execution time');
assert.match(resetService, /permissions\.canManageDatabase !== true/, 'reset service must enforce database permission');
assert.match(resetService, /permissions\.canManageSettings !== true/, 'reset service must enforce settings permission');
assert.match(resetService, /terminate\(db\)/, 'factory reset must terminate Firestore before clearing persistent cache');
assert.match(resetService, /clearIndexedDbPersistence\(db\)/, 'factory reset must clear persistent Firestore cache before reload');
assert.match(resetService, /resetAppConfigToFactoryDefaults/, 'factory reset must persist a known default configuration');
assert.match(resetService, /Factory reset verification failed/, 'factory reset must verify destructive operations');
assert.match(resetComponent, /isAdminOrOwner/, 'factory reset UI must be admin/owner only');
assert.match(resetComponent, /permissions\.canManageDatabase/, 'factory reset UI must require database permission');
assert.doesNotMatch(resetComponent, /user\?\.email\?\.toLowerCase\(\) === 'b\.b\.thodsawat@gmail\.com'/, 'factory reset UI must not use an email-only authorization bypass');
assert.match(resetComponent, /await assertFactoryResetAuthorized\(\)/, 'UI must revalidate authorization immediately before destructive work');
assert.match(resetComponent, /factory_reset_started/, 'factory reset must create an audit trail');
assert.match(resetComponent, /factory_reset_failed/, 'failed factory reset must be auditable');
assert.match(resetComponent, /ไม่สมบูรณ์/, 'factory reset must never show false success after a failure');

console.log('Cloud sync and factory reset integrity checks passed');
